<script type="text/x-magento-template" id="fastly-create-log-endpoint-template-https">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("Your log endpoint will be created in version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="create-log-endpoint-form"
          name="create-log-endpoint-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_log_endpoint" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_log_endpoint"
                               id="fastly_activate_log_endpoint"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_log_endpoint"></label>
                    </div>
                </div>
            </div>
            <div class="admin__field field">
                <label for="condition" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Condition") ?></span>
                </label>
                <div class="admin__field-control">
                    <span id="attach_span" style>
                        This will happen all the time unless you <a id="attach" href="#">Attach a condition</a>
                    </span>
                    <select name="conditions" id="conditions" class="admin__control-select"></select>
                    <div class="admin__field-note"><a id="detach" href="#">Detach condition</a> <span id="sep">|</span>
                        <a id="create-response-condition" href="#">Create a new response condition</a>
                    </div>
                    <input type="hidden" name="condition_name" id="condition_name"/>
                    <input type="hidden" name="apply_if" id="apply_if"/>
                    <input type="hidden" name="condition_priority" id="condition_priority"/>
                </div>
            </div>
            <input type="hidden" name="endpoint_type">
            <input type="hidden" name="old_name">
            <div class="admin__field field _required">
                <label for="log_endpoint[name]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="log_endpoint[name]" id="log_endpoint[name]" class="admin__control-text required-entry">
                    <div class="admin__field-note">
                        The name of your endpoint, such as <b>My endpoint</b>.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="log_endpoint[url]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("URL") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="log_endpoint[url]" id="log_endpoint[url]" class="admin__control-text required-entry">
                    <div class="admin__field-note">
                        The URL to send logs to. Must use HTTPS.
                    </div>
                </div>
            </div>
            <div class="admin__field field">
                <label for="log_endpoint[format]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Log format") ?></span>
                </label>
                <div class="admin__field-control">
                    <textarea rows="6" name="log_endpoint[format]" id="log_endpoint[format]" class="admin__control-text">
 %h %l %u %t "%r" %>s %b</textarea>
                    <div class="admin__field-note">
                        An Apache-style string or VCL variables to use for log formatting (the Apache Common Log format string appears by default).
                        See <a target="_blank" href="https://docs.fastly.com/en/guides/setting-up-remote-log-streaming" rel="noopener noreferrer" class="external-link">Fastly's log files docs</a>,
                        <a target="_blank" href="https://www.varnish-cache.org/docs/2.1/reference/vcl.html#variables" rel="noopener noreferrer" class="external-link">Varnish's descriptions of VCL variables</a>,
                        and <a target="_blank" href="https://docs.fastly.com/vcl/variables/" rel="noopener noreferrer" class="external-link">Fastly's available VCL variables</a> for more info.
                    </div>
                </div>
            </div>
            <div class="admin__field field ">
                <label for="log_endpoint[content_type]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Content type") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="log_endpoint[content_type]" id="log_endpoint[content_type]" class="admin__control-text">
                    <div class="admin__field-note">
                        <?php /* @noEscape */ echo __("Content type of the header sent with the request.") ?>
                    </div>
                </div>
            </div>
            <div class="admin__field field">
                <label for="log_endpoint[header_name]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Header Name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="log_endpoint[header_name]" id="log_endpoint[header_name]" class="admin__control-text">
                    <div class="admin__field-note">
                        <?php /* @noEscape */ echo __("Name of the custom header sent with the request.") ?>
                    </div>
                </div>
            </div>
            <div class="admin__field field">
                <label for="log_endpoint[header_value]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Header Value") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="log_endpoint[header_value]" id="log_endpoint[header_value]" class="admin__control-text">
                    <div class="admin__field-note">
                        Value of the custom header sent with the request.
                    </div>
                </div>
            </div>
            <div class="admin__field field">
                <label for="log_endpoint[json_format]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("JSON Format") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="log_endpoint[json_format]" id="log_endpoint[json_format]" class="admin__control-text">
                        <option value="0" selected>Disabled</option>
                        <option value="1">Array of JSON. Wraps JSON log batches in an array</option>
                        <option value="2">Newline delimited JSON. Places each JSON log entry onto a new line in a batch</option>
                    </select>
                    <div class="admin__field-note">
                        Enforces valid JSON formatting for log entries.
                    </div>
                </div>
            </div>
            <div class="admin__field field">
                <label for="log_endpoint[message_type]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Message Type") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="log_endpoint[message_type]" id="log_endpoint[message_type]" class="admin__control-text">
                        <option value="classic" selected>Classic</option>
                        <option value="loggly">Loggly</option>
                        <option value="logplex">Logplex</option>
                        <option value="blank">Blank</option>
                    </select>
                    <div class="admin__field-note">
                        <a target="_blank" href="https://docs.fastly.com/en/guides/changing-log-line-formats" rel="noopener noreferrer" class="external-link">Learn more about changing log line formats</a>
                    </div>
                </div>
            </div>
            <div class="admin__field field">
                <label for="log_endpoint[method]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Method") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="log_endpoint[method]" id="log_endpoint[method]" class="admin__control-text">
                        <option value="POST" selected>POST</option>
                        <option value="PUT">PUT</option>
                    </select>
                    <div class="admin__field-note">
                        HTTP method used for request.
                    </div>
                </div>
            </div>
            <div class="admin__field field">
                <label for="log_endpoint[period]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Period") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="log_endpoint[period]" id="log_endpoint[period]" class="admin__control-text" value="5">
                    <div class="admin__field-note">
                        How frequently, in seconds, batches of log data are sent to the HTTPS endpoint. A value of 0 sends logs at the same interval as the default, which is 5 seconds.
                    </div>
                </div>
            </div>
            <div class="admin__field field ">
                <label for="log_endpoint[request_max_bytes]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Request Max Bytes") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="log_endpoint[request_max_bytes]" id="log_endpoint[request_max_bytes]" class="admin__control-text" value="0">
                    <div class="admin__field-note">
                        The maximum number of bytes sent in one request. Defaults 0 (100MB).
                    </div>
                </div>
            </div>
            <div class="admin__field field ">
                <label for="log_endpoint[request_max_entries]" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Request Max Entries") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="log_endpoint[request_max_entries]" id="log_endpoint[request_max_entries]" class="admin__control-text" value="0">
                    <div class="admin__field-note">
                        The maximum number of logs sent in one request. Defaults 0 (10k).
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>
