<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Copied from Mage_Config::view/adminhtml/templates/system/config/form/field/array.phtml.
 * Currently necessary for work around a missing feature in the M2 core.
 *
 * @see https://github.com/magento/magento2/pull/3469
 */
?>

<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
?>

<div class="design_theme_ua_regexp" id="grid<?php /* @noEscape */ echo $_htmlId; ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?php /* @noEscape */ echo $block->getElement()->getId(); ?>">
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                    <th><?php /* @noEscape */ echo $column['label']; ?></th>
                <?php endforeach;?>
                <th class="col-actions" colspan="<?php /* @noEscape */ echo $_colspan; ?>">Action</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="<?php /* @noEscape */ echo count($block->getColumns())+$_colspan; ?>"
                    class="col-actions-add">
                    <button id="addToEndBtn<?php /* @noEscape */ echo $_htmlId; ?>"
                            class="action-add"
                            title="<?php /* @noEscape */ echo __('Add'); ?>"
                            type="button">
                        <span>
                            <?php /* @noEscape */ echo $block->getAddButtonLabel(); ?>
                            <?php /* @noEscape */ echo __('Add'); ?>
                        </span>
                    </button>
                </td>
            </tr>
            </tfoot>
            <tbody id="addRow<?php /* @noEscape */ echo $_htmlId; ?>"></tbody>
        </table>
    </div>
    <input type="hidden" name="<?php /* @noEscape */ echo $block->getElement()->getName(); ?>[__empty]" value="" />

    <script>
        require([
            'mage/template',
            'prototype'
        ], function (mageTemplate) {
        // create row creator
        window.arrayRow<?php /* @noEscape */ echo $_htmlId ?> = {

            // define row prototypeJS template
            template: mageTemplate(
                    '<tr id="<%- _id %>">'
                    <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                            + '<td>'
                            + '<?php /* @noEscape */ echo $block->renderCellTemplate($columnName)?>'
                            + '<\/td>'
                        <?php endforeach; ?>

                    <?php if ($block->isAddAfter()) : ?>
                            + '<td><button class="action-add" type="button" id="addAfterBtn<%- _id %>">'
                            + '<span><?php /* @noEscape */ echo __('Add after'); ?><\/span><\/button><\/td>'
                        <?php endif; ?>

                            + '<td class="col-actions"><button onclick="'
                            + 'arrayRow<?php /* @noEscape */ echo $_htmlId ?>'
                            + '.del(\'<%- _id %>\')" class="action-delete" type="button">'
                            + '<span><?php /* @noEscape */ echo __('Delete'); ?><\/span><\/button><\/td>'
                            + '<\/tr>'
            ),

            add: function(rowData, insertAfterId) {
                // generate default template data
                var templateValues;

                // Prepare template values
                if (rowData) {
                    templateValues = rowData;
                } else {
                    var d = new Date();
                    templateValues = {
                <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                    <?php /* @noEscape */ echo $columnName ?>: '',
                        'option_extra_attrs': {},
                    <?php endforeach; ?>
                        _id: '_' + d.getTime() + '_' + d.getMilliseconds()
                };
            }

            // Insert new row after specified row or at the bottom
            if (insertAfterId) {
            Element.insert($(insertAfterId), {after: this.template(templateValues)});
        } else {
            Element.insert($('addRow<?php /* @noEscape */ echo $_htmlId ?>'), {bottom: this.template(templateValues)});
        }

        // Fill controls with data
        if (rowData) {
            var rowInputElementNames = Object.keys(rowData.column_values);
            for (var i = 0; i < rowInputElementNames.length; i++) {
                if ($(rowInputElementNames[i])) {
                    $(rowInputElementNames[i]).value = rowData.column_values[rowInputElementNames[i]];
                }
            }
        }

        // Add event for {addAfterBtn} button
        <?php if ($block->isAddAfter()) : ?>
        Event.observe('addAfterBtn' + templateValues._id, 'click', this.add.bind(this, false, templateValues._id));
            <?php endif; ?>
        },

        del: function(rowId) {
            $(rowId).remove();
        }
        }

        // bind add action to "Add" button in last row
        Event.observe(
            'addToEndBtn<?php /* @noEscape */ echo $_htmlId ?>',
            'click',
            arrayRow<?php /* @noEscape */ echo $_htmlId ?>.add.bind(
                arrayRow<?php /* @noEscape */ echo $_htmlId ?>, false, false
            )
        );

        // add existing rows
        <?php
        foreach ($block->getArrayRows() as $_rowId => $_row) {
            /* @noEscape */ echo "arrayRow{$_htmlId}.add(" . $_row->toJson() . ");\n";
        }
        ?>

        // Toggle the grid availability, if element is disabled (depending on scope)
        <?php if ($block->getElement()->getDisabled()) :?>
        toggleValueElements({checked: true}, $('grid<?php /* @noEscape */ echo $_htmlId; ?>').parentNode);
            <?php endif;?>
        });
    </script>
</div>
