<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Copied from Mage_Config::view/adminhtml/templates/system/config/form/field/array.phtml.
 * Currently necessary for work around a missing feature in the M2 core.
 *
 * @see https://github.com/magento/magento2/pull/3469
 */
?>

<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
?>

<button type="button" style="margin-bottom: 10px;" class="primary" id="add-auth-container-button">
    <?php /* @noEscape */ echo __('Manage users') ?>
</button>
<div class="design_theme_ua_regexp" id="grid<?php /* @noEscape */  echo $_htmlId; ?>">
</div>
<button class="action-delete remove_auth_dictionary"
        title="<?php /* @noEscape */ echo __('Delete') ?>"
        type="button">
    <span><?php /* @noEscape */ echo __('Remove all users') ?></span>
</button>

<div class="message message-error fastly-button-messages"
     id="fastly-error-auth-list-button-msg"
     style="display: none"></div>
<div class="message message-success fastly-button-messages"
     id="fastly-success-auth-list-button-msg"
     style="display: none">

<style type="text/css">
    .admin__control-table .fastly-edit-dictionary-icon::before {
        content: '\e610';
        font-size: 2rem;
    }

    .no-dictionaries, .loading-dictionaries {
        text-align: center;
    }
</style>
