<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Copied from Mage_Config::view/adminhtml/templates/system/config/form/field/array.phtml.
 * Currently necessary for work around a missing feature in the M2 core.
 *
 * @see https://github.com/magento/magento2/pull/3469
 */

// @codingStandardsIgnoreFile

?>

<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
?>

<div class="design_theme_ua_regexp" id="grid<?php /* @escapeNotVerified */ echo $_htmlId; ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?php /* @escapeNotVerified */ echo $block->getElement()->getId(); ?>">
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <th><?php /* @escapeNotVerified */ echo $column['label']; ?></th>
                <?php endforeach;?>
                <th class="col-actions" colspan="<?php /* @escapeNotVerified */ echo $_colspan; ?>">Action</th>
            </tr>
            </thead>
            <tbody id="fastly-backends-list"></tbody>
        </table>
    </div>
    <input type="hidden" name="<?php /* @escapeNotVerified */ echo $block->getElement()->getName(); ?>[__empty]" value="" />
</div>

<style type="text/css">
    .admin__control-table .fastly-edit-backend-icon::before {
        content: '\e610';
        font-size: 2rem;
    }
</style>
