<ul class="checkboxes">
    <?php foreach ($block->getValues() as $name => $label) : ?>
        <li>
            <input type="checkbox" value="<?= /* @noEscape */ $name?>"
                   data-validate="{required:true}"
                   name="<?= /* @noEscape */ $block->getNamePrefix() ?>[]"
                   id="<?= /* @noEscape */ $block->getHtmlId() . '_' . $name ?>"
                <?= /* @noEscape */ ($block->getIsChecked($name) ? ' checked="checked"' : '') ?>/>
            <label for="<?= /* @noEscape */ $block->getHtmlId() . '_' . $name ?>">
                <?= /* @noEscape */ $label ?>
            </label>
        </li>
    <?php endforeach;?>
</ul>