<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Copied from Mage_Config::view/adminhtml/templates/system/config/form/field/array.phtml.
 * Currently necessary for work around a missing feature in the M2 core.
 *
 * @see https://github.com/magento/magento2/pull/3469
 */

// @codingStandardsIgnoreFile

?>

<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
$authEnabled = $this->isAuthEnabled();
$msg = !($authEnabled) ? 'Click to Enable' : 'Click to Disable';
?>

<button type="button" style="margin-bottom: 10px;" class="primary" data-status="<?php echo $authEnabled; ?>" id="enable-auth-container-button"><?php echo __($msg) ?></button>
<div class="design_theme_ua_regexp" id="grid<?php /* @escapeNotVerified */ echo $_htmlId; ?>">
</div>

<div class="message message-error fastly-button-messages" id="fastly-error-auth-enable-button-msg" style="display: none"></div>

<div class="message message-success fastly-button-messages" id="fastly-success-auth-enable-button-msg" style="display: none"></div>

<style type="text/css">
    .admin__control-table .fastly-edit-dictionary-icon::before {
        content: '\e610';
        font-size: 2rem;
    }

    .no-dictionaries, .loading-dictionaries {
        text-align: center;
    }
</style>
