<?php echo $block->getButtonHtml() ?>

<div class="message message-error fastly-button-messages"
     id="fastly-error-export-button-msg"
     style="display: none">
</div>

<div class="message message-success fastly-button-messages"
     id="fastly-success-export-button-msg"
     style="display: none">
</div>

<div class="message message-warning fastly-button-messages"
     id="fastly-warning-export-button-msg"
     style="display: none">
</div>

<style type="text/css">
    .fastly-button-messages {
        font-size: 1.2rem;
        margin-top: 5px;
        padding: 1.4rem 4rem 1.4rem 5.5rem;
    }

    .admin__control-table .export-list-icon::before {
        content: '\2630';
        font-size: 1.3rem;
        margin-left: 6px;
    }

    .export-field {
        margin-left: calc( (100%) * 0.25 - 30px ) !important;
    }

    .export-note {
        margin-left: calc( (100%) * 0.25 ) !important;
        color: #999999;
    }

    .export-checkbox {
        margin-top: 6px !important;
    }
</style>