<?php echo $block->getButtonHtml(); ?>

<p class="note">
    <span>It is required to push config to VCL and activate it before activating the image optimization feature.</span>
</p>

<div class="message message-error fastly-button-messages" id="fastly-error-image-button-msg" style="display: none">
</div>

<div class="message message-success fastly-button-messages" id="fastly-success-image-button-msg" style="display: none">
</div>
