<?php
?>

<button type="button"
        style="margin-bottom: 10px;"
        class="secondary"
        id="override-host-container-button">
    <?php /* @noEscape */ echo __('Configure') ?>
</button>

<div class="message message-error fastly-button-messages"
     id="fastly-error-override-host-button-msg"
     style="display: none"></div>

<div class="message message-success fastly-button-messages"
     id="fastly-success-override-host-button-msg"
     style="display: none"></div>

<div class="message message-warning fastly-button-messages"
     id="fastly-warning-override-host-button-msg"
     style="display: none"></div>
