<?php echo $block->getButtonHtml() ?>

<div class="message message-error fastly-button-messages" id="fastly-test-error-button-msg" style="display: none">
</div>

<div class="message message-success fastly-button-messages" id="fastly-test-success-button-msg" style="display: none">
</div>

<div class="message message-warning fastly-button-messages" id="fastly-test-warning-button-msg" style="display: none">
</div>

<style type="text/css">
    .fastly-button-messages {
        font-size: 1.2rem;
        margin-top: 5px;
        padding: 1.4rem 4rem 1.4rem 5.5rem;
    }
</style>
