<button type="button"
        style="margin-bottom: 10px;"
        class="secondary"
        id="tls-domains-button">
    <?php /* @noEscape */ echo __('Configure') ?>
</button>

<div class="message message-error fastly-button-messages"
     id="fastly-error-tls-domains-button"
     style="display: none"></div>

<div class="message message-success fastly-button-messages"
     id="fastly-success-tls-domains-button"
     style="display: none"></div>

<div class="message message-warning fastly-button-messages"
     id="fastly-warning-tls-domains-button"
     style="display: none"></div>