<?php
    $_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
    $_colspan = $block->isAddAfter() ? 2 : 1;
?>
<button type="button"
        style="margin-bottom: 10px;"
        class="secondary"
        id="list-versions-container-button">
    <?= /* @noEscape */ __('List all versions') ?>
</button>

<div class="message message-error fastly-button-messages"
     id="fastly-error-versions-button-msg"
     style="display: none"></div>

<div class="message message-success fastly-button-messages"
     id="fastly-success-dictionary-button-msg"
     style="display: none"></div>

<div class="message message-warning fastly-button-messages"
     id="fastly-warning-dictionary-button-msg"
     style="display: none"></div>

<style type="text/css">
    .admin__control-table .fastly-edit-dictionary-icon::before {
        content: '\e610';
        font-size: 2rem;
    }

    .admin__control-table .fastly-delete-dictionary-icon::before {
        content: '\e630';
        font-size: 2rem;
    }

    .no-dictionaries, .loading-dictionaries {
        text-align: center;
    }
</style>
