<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!-- Upload VCL overlay template -->
<script type="text/x-magento-template" id="fastly-uploadvcl-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll upload your VCL to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate VCL after upload')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_vcl"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Force TLS toggle overlay template -->
<script type="text/x-magento-template" id="fastly-tls-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_tls"
                               id="fastly_activate_tls"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Image Optimization toggle overlay template -->
<script type="text/x-magento-template" id="fastly-image-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-warning" id="fastly-image-template-notifications" style="display: none"></div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl"
                       class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span></label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_image_vcl"
                               id="fastly_activate_image_vcl" checked/>
                        <label class="admin__field-label" for="fastly_activate_image_vcl"></label>
                    </div>
                </div>
            </div>
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_image_quality_flag"
                       class="admin__field-label">
                    <span>
                        <?php /* @noEscape */ echo __('Set image quality to Magento default')?>
                    </span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_image_quality_flag"
                               id="fastly_image_quality_flag" checked/>
                        <label class="admin__field-label" for="fastly_image_quality_flag"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Blocking toggle overlay template -->
<script type="text/x-magento-template" id="fastly-blocking-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_blocking"
                               id="fastly_activate_blocking"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_blocking"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Delete Custom Snippet overlay template -->
<script type="text/x-magento-template" id="fastly-delete-custom-snippet-template">
    <div class="messages">
        <div class="message message-notice fastly-message-notice" style="display: none">
        </div>
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_delete_custom_snippet_activate"
                               id="fastly_delete_custom_snippet_activate"
                               checked/>
                        <label class="admin__field-label" for="fastly_delete_custom_snippet_active"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- WAF Bypass toggle overlay template -->
<script type="text/x-magento-template" id="fastly-waf-bypass-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_waf_bypass"
                               id="fastly_activate_waf_bypass"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_waf_bypass"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Basic Authentication toggle overlay template -->
<script type="text/x-magento-template" id="fastly-auth-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error"
             id="fastly-auth-toggle-message-error"
             style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_auth"
                               id="fastly_activate_auth"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_auth"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Backend configuration overlay template -->
<script type="text/x-magento-template" id="fastly-backend-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("Your backend will be reconfigured in version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="backend-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <input hidden="hidden" name="backend_name" id="backend_name" class="admin__control-text">
            <div class="admin__field field">
                <label for="shield" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Shield") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="shield" id="backend_shield" class="admin__control-text">
                        <option value="">(none)</option>
                        <option value="fjr-ae">AE, Fujairah Al Mahta - Dubai</option>
                        <option value="brisbane-au">AU, Brisbane</option>
                        <option value="melbourne-au">AU, Melbourne</option>
                        <option value="perth-au">AU, Perth</option>
                        <option value="sydney-au">
                            AU, Sydney - Recommended for AWS ap-southeast-2, GCP australia-southeast1 origins
                        </option>
                        <option value="gru-br-sa">
                            BR, Sao Paulo - Recommended for AWS sa-east-1, GCP southamerica-east1
                        </option>
                        <option value="yyz-on-ca">CA, Toronto</option>
                        <option value="yul-montreal-ca">
                            CA, Montreal - Recommended for AWS ca-central-1, GCP northamerica-northeast1 origins
                        </option>
                        <option value="mad-madrid-es">ES, Madrid</option>
                        <option value="hel-helsinki-fi">FI, Helsinki - Recommended for GCP europe-north1</option>
                        <option value="cdg-par-fr">FR, Paris- Recommended for AWS eu-west3</option>
                        <option value="hongkong-hk">HK, Hong Kong</option>
                        <option value="hhn-frankfurt-de">
                            DE, Frankfurt - Interxion - Recommended for GCP europe-west3 origins
                        </option>
                        <option value="frankfurt-de">DE, Frankfurt - Recommended for AWS eu-central1 origins</option>
                        <option value="tyo-tokyo-jp">JP, Tokyo - Recommended for AWS ap-northeast-1 origins</option>
                        <option value="osaka-jp">JP, Osaka - Recommened for AWS ap-northeast-3 origins</option>
                        <option value="amsterdam-nl">NL, Amsterdam - Recommended for GCP eu-west1/4 origins</option>
                        <option value="auckland-akl">NZ, Auckland</option>
                        <option value="wellington-wlg">NZ, Wellington</option>
                        <option value="stockholm-bma">SE, Stockholm</option>
                        <option value="singapore-sg">
                            SG, Singapore - Recommended for AWS ap-southeast-1, GCP asia-southeast1 origins
                        </option>
                        <option value="london_city-uk">
                            UK, London - LCY - Recommended for AWS eu-west1/2 origins
                        </option>
                        <option value="london-uk">UK, London - LHR - Recommended for GCP eu-west2 origins</option>
                        <option value="atl-ga-us">US, Atlanta, GA</option>
                        <option value="bos-ma-us">US, Boston, MA</option>
                        <option value="mdw-il-us">US, Chicago, IL - Recommended for GCP us-central1 origins</option>
                        <option value="den-co-us">US, Denver, CO</option>
                        <option value="dallas-tx-us">US, Dallas, TX</option>
                        <option value="iah-tx-us">US, Houston, TX</option>
                        <option value="iad-va-us">
                            US, Washington, DC - deprecated
                        </option>
                        <option value="bwi-va-us">
                            US, Washington, DC - Recommended for AWS us-east1, GCP us-east1/4 origins
                        </option>
                        <option value="lax-ca-us">US, Los Angeles, CA - Recommended for GCP us-west2</option>
                        <option value="miami-fl-us">US, Miami, FL</option>
                        <option value="jfk-ny-us">US, New York City, NY</option>
                        <option value="sjc-ca-us">US, San Jose, CA</option>
                        <option value="sea-wa-us">
                            US, Seattle, WA - Recommended for AWS us-west2, GCP us-west1 origins
                        </option>
                        <option value="cpt-capetown-za">ZA, Capetown</option>
                        <option value="jnb-johannesburg-za">ZA, Johannesburg</option>
                    </select>
                    <div class="admin__field-note">
                        The shield POP designated to reduce inbound load on this origin by serving the cached data to
                        the rest of the network.
                        <a href="https://docs.fastly.com/guides/performance-tuning/shielding"
                           target="_blank">Click for more details.</a>
                    </div>
                </div>
            </div>

            <div class="admin__field field _required">
                <label for="connect_timeout" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Connect timeout") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="connect_timeout"
                           type="number"
                           required="required"
                           id="backend_connect_timeout"
                           class="admin__control-text
                                    required-entry
                                    validate-alphanum-with-spaces
                                    validate-length
                                    maximum-length-50">
                    <div class="admin__field-note">How long to wait for a timeout in milliseconds.</div>
                </div>
            </div>

            <div class="admin__field field _required">
                <label for="between_bytes_timeout" class="admin__field-label">
                    <span><?php /* @noEscape */  echo __("Between bytes timeout") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="between_bytes_timeout"
                           type="number"
                           required="required"
                           id="backend_between_bytes_timeout"
                           class="admin__control-text">
                    <div class="admin__field-note">How long to wait between bytes in milliseconds.</div>
                </div>
            </div>

            <div class="admin__field field _required">
                <label for="first_byte_timeout " class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("First byte timeout ") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="first_byte_timeout"
                           type="number"
                           required="required"
                           id="backend_first_byte_timeout"
                           class="admin__control-text">
                    <div class="admin__field-note">How long to wait for the first bytes in milliseconds.</div>
                </div>
            </div>

            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_backend" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_backend"
                               id="fastly_activate_backend"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_backend"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Backend creation overlay template -->
<script type="text/x-magento-template" id="fastly-create-backend-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("Your backend will be created in version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="create-backend-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_backend" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_backend"
                               id="fastly_activate_backend"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_backend"></label>
                    </div>
                </div>
            </div>
            <div class="admin__field field">
                <label for="condition" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Condition") ?></span>
                </label>
                <div class="admin__field-control">
                    <span id="attach_span" style>
                        This will happen all the time unless you <a id="attach" href="#">Attach a condition</a>
                    </span>
                    <select name="conditions" id="conditions" class="admin__control-select"></select>
                    <div class="admin__field-note"><a id="detach" href="#">Detach condition</a> <span id="sep">|</span>
                        <a id="create-condition" href="#">Create a new request condition</a>
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="backend_name" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="backend_name" id="backend_name" class="admin__control-text">
                    <div class="admin__field-note">
                        The name of your origin, such as <b>My origin server</b>.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="backend_address" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Address") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="backend_address" id="backend_address" class="admin__control-text">
                    <div class="admin__field-note">
                        The IP address (or hostname) for your origin server.
                    </div>
                </div>
            </div>

            <div class="admin__field field">
                <label for="shield" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Shielding") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="shield" id="backend_shield" class="admin__control-select">
                        <option value="">(none)</option>
                        <option value="fjr-ae">AE, Fujairah Al Mahta - Dubai</option>
                        <option value="brisbane-au">AU, Brisbane</option>
                        <option value="melbourne-au">AU, Melbourne</option>
                        <option value="perth-au">AU, Perth</option>
                        <option value="sydney-au">
                            AU, Sydney - Recommended for AWS ap-southeast-2, GCP australia-southeast1 origins
                        </option>
                        <option value="gru-br-sa">
                            BR, Sao Paulo - Recommended for AWS sa-east-1, GCP southamerica-east1
                        </option>
                        <option value="yyz-on-ca">CA, Toronto</option>
                        <option value="yul-montreal-ca">
                            CA, Montreal - Recommended for AWS ca-central-1, GCP northamerica-northeast1 origins
                        </option>
                        <option value="mad-madrid-es">ES, Madrid</option>
                        <option value="hel-helsinki-fi">FI, Helsinki - Recommended for GCP europe-north1</option>
                        <option value="cdg-par-fr">FR, Paris- Recommended for AWS eu-west3</option>
                        <option value="hongkong-hk">HK, Hong Kong</option>
                        <option value="hhn-frankfurt-de">
                            DE, Frankfurt - Interxion - Recommended for GCP europe-west3 origins
                        </option>
                        <option value="frankfurt-de">DE, Frankfurt - Recommended for AWS eu-central1 origins</option>
                        <option value="tokyo-jp2">JP, Tokyo - deprecated</option>
                        <option value="tyo-tokyo-jp">JP, Tokyo - Recommended for AWS ap-northeast-1 origins</option>
                        <option value="osaka-jp">JP, Osaka - Recommened for AWS ap-northeast-3 origins</option>
                        <option value="amsterdam-nl">NL, Amsterdam - Recommended for GCP eu-west1/4 origins</option>
                        <option value="auckland-akl">NZ, Auckland</option>
                        <option value="wellington-wlg">NZ, Wellington</option>
                        <option value="stockholm-bma">SE, Stockholm</option>
                        <option value="singapore-sg">
                            SG, Singapore - Recommended for AWS ap-southeast-1, GCP asia-southeast1 origins
                        </option>
                        <option value="london_city-uk">
                            UK, London - LCY - Recommended for AWS eu-west1/2 origins
                        </option>
                        <option value="london-uk">UK, London - LHR - Recommended for GCP eu-west2 origins</option>
                        <option value="atl-ga-us">US, Atlanta, GA</option>
                        <option value="bos-ma-us">US, Boston, MA</option>
                        <option value="mdw-il-us">US, Chicago, IL - Recommended for GCP us-central1 origins</option>
                        <option value="den-co-us">US, Denver, CO</option>
                        <option value="dallas-tx-us">US, Dallas, TX</option>
                        <option value="iah-tx-us">US, Houston, TX</option>
                        <option value="iad-va-us">
                            US, Washington, DC - deprecated
                        </option>
                        <option value="bwi-va-us">
                            US, Washington, DC - Recommended for AWS us-east1, GCP us-east1/4 origins
                        </option>
                        <option value="lax-ca-us">US, Los Angeles, CA - Recommended for GCP us-west2</option>
                        <option value="miami-fl-us">US, Miami, FL</option>
                        <option value="jfk-ny-us">US, New York City, NY</option>
                        <option value="sjc-ca-us">US, San Jose, CA</option>
                        <option value="sea-wa-us">
                            US, Seattle, WA - Recommended for AWS us-west2, GCP us-west1 origins
                        </option>
                        <option value="cpt-capetown-za">ZA, Capetown</option>
                        <option value="jnb-johannesburg-za">ZA, Johannesburg</option>
                    </select>
                    <div class="admin__field-note">
                        The shield POP designated to reduce inbound load on this origin by serving the cached data to
                        the rest of the network.
                        <a href="https://docs.fastly.com/guides/performance-tuning/shielding"
                           target="_blank">Click for more details.</a>
                    </div>
                </div>
            </div>

            <div class="admin__field field">
                <label for="shield" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Auto load balance") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="auto_loadbalance" id="auto_loadbalance" class="admin__control-select">
                        <option value="0">No</option>
                        <option value="1">Yes</option>
                    </select>
                    <div class="admin__field-note">
                        Enables Fastly to
                        <a href="https://docs.fastly.com/guides/basic-configuration/health-checks-tutorial"
                           target="_blank">load balance between two or more backend hosts.</a>
                    </div>
                </div>
            </div>

            <div class="admin__field field _required weight">
                <label for="weight" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Weight") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="weight" id="weight" class="admin__control-text" value="100">
                    <div class="admin__field-note">
                        A portion of traffic to send to a specific origin. Each origin receives (weight ÷ total weight
                        across origins) of the traffic.
                    </div>
                </div>
            </div>

            <div class="admin__fieldset recommended">
                <div class="admin__fieldset message-recommend">
                    <div class="admin__field field" id="recommended-title">
                        <label class="admin__field-label">
                            RECOMMENDED Transport Layer Security (TLS)
                        </label>
                    </div>
                </div>

                <div class="admin__field field">
                    <label for="tls-radio" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Enable TLS?") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <table>
                            <tr>
                                <td>
                                    <input type="radio" id="tls-yes" class="admin__control-radio" name="tls-radio"
                                           value="1" checked/>
                                    <label class="admin__field-label" for="tls-yes">
                                        <b>Yes,</b> enable TLS and connect securely using port
                                    </label>
                                </td>
                                <td>
                                    <input name="tls-yes-port"
                                           type="number"
                                           required="required"
                                           id="tls-yes-port"
                                           class="admin__control-text
                                        required-entry
                                        validate-alphanum-with-spaces
                                        validate-length
                                        maximum-length-50
                                        checkbox-input"
                                           value="443">
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="radio" id="tls-no" class="admin__control-radio" name="tls-radio"
                                           value="0"/>
                                    <label class="admin__field-label" for="tls-no">
                                        <b>No, do not enable TLS.</b> Instead connect using port &nbsp
                                    </label>
                                </td>
                                <td>
                                    <input name="tls-no-port"
                                           type="number"
                                           required="required"
                                           id="tls-no-port"
                                           class="admin__control-text
                                        required-entry
                                        validate-alphanum-with-spaces
                                        validate-length
                                        maximum-length-50
                                        checkbox-input"
                                           value="80">
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>

                <div class="admin__field field">
                    <label for="certificate-radio" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Verify certificate?") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="radio" id="certificate-yes" class="admin__control-radio" name="certificate-radio"
                               value="1" checked/>
                        <label class="admin__field-label" for="certificate-yes">
                            <b>Yes,</b> verify the authenticity of the TLS certificate
                        </label>
                    </div>
                    <div class="admin__field-control">
                        <input type="radio" id="certificate-no" class="admin__control-radio" name="certificate-radio"
                               value="0"/>
                        <label class="admin__field-label" for="certificate-no">
                            <b>No,</b> do not verify my TLS certificate
                        </label>
                        <div class="admin__field-note" id="certificate-no-msg"></div>
                    </div>
                </div>

                <div class="admin__field field _required">
                    <label for="certificate-hostname" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Certificate hostname") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input name="certificate-hostname"
                               type="text"
                               required="required"
                               id="certificate-hostname"
                               class="admin__control-text"
                        >
                        <div class="admin__field-note">This value is matched against the certificate common name (CN)
                            or a subject alternate name (SAN).</div>
                    </div>
                </div>

                <div class="admin__field field">
                    <label for="sni-hostname" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("SNI hostname") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input name="sni-hostname"
                               type="text"
                               id="sni-hostname"
                               class="admin__control-text"
                        >
                        <div class="admin__field-option">
                            <input class="admin__control-checkbox"
                                   type="checkbox"
                                   name="match-sni"
                                   id="match-sni"/>
                            <label class="admin__field-label" for="match-sni">Match the SNI hostname to the Certificate
                                hostname. This value identifies which certificate is to be used for the request to
                                origin.
                            </label>
                        </div>
                    </div>
                </div>

                <div class="admin__field field">
                    <label for="tls-ca-certificate" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("TLS CA certificate") ?></span>
                    </label>
                    <div class="admin__field-control">
                    <textarea rows="6"
                              name="tls-ca-certificate"
                              required="required"
                              id="tls-ca-certificate"
                              class="admin__control-text"></textarea>
                        <div class="admin__field-note">CA certificate used to verify the certificate from origin.
                            Must be in PEM form.</div>
                    </div>
                </div>

                <div class="admin__field field">
                    <label class="admin__field-label">
                        Advanced TLS options
                    </label>
                </div>

                <div class="admin__field field">
                    <label for="minimum-tls" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Minimum TLS version") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select name="minimum-tls" id="minimum-tls" class="admin__control-text">
                            <option value="">none</option>
                            <option value="1.0">1.0</option>
                            <option value="1.1">1.1</option>
                            <option value="1.2">1.2</option>
                        </select>
                        <div class="admin__field-note">The minimum TLS protocol version that Fastly will use to
                            connect to your origin server.</div>
                    </div>
                </div>

                <div class="admin__field field">
                    <label for="maximum-tls" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Maximum TLS version") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <select name="maximum-tls" id="maximum-tls" class="admin__control-text">
                            <option value="">none</option>
                            <option value="1.0">1.0</option>
                            <option value="1.1">1.1</option>
                            <option value="1.2">1.2</option>
                        </select>
                        <div class="admin__field-note">The maximum TLS protocol version that Fastly will use to
                            connect to your origin server. (Must be higher than the minimum TLS version.)</div>
                    </div>
                </div>

                <div class="admin__field field">
                    <label for="ciphersuites" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("Ciphersuites") ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input name="ciphersuites"
                               type="text"
                               id="ciphersuites"
                               class="admin__control-text"
                        >
                        <div class="admin__field-note">A list of OpenSSL ciphers to use when connecting to your origin.
                            For more information see the OpenSSL documentation on cipher list format</div>
                    </div>
                </div>

                <div class="admin__field field">
                    <label for="tls-client-certificate" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("TLS client certificate") ?></span>
                    </label>
                    <div class="admin__field-control">
                    <textarea rows="6"
                              name="tls-client-certificate"
                              required="required"
                              id="tls-client-certificate"
                              class="admin__control-text"></textarea>
                        <div class="admin__field-note">Certificate used to authenticate to the origin server. Must be in
                            PEM form, and must be accompanied by a client key. It is advised to not used keys from
                            anywhere else. A client certificate and client key allows your server to authenticate that
                            Fastly is performing the connection.
                        </div>
                    </div>
                </div>

                <div class="admin__field field">
                    <label for="tls-client-key" class="admin__field-label">
                        <span><?php /* @noEscape */ echo __("TLS client key") ?></span>
                    </label>
                    <div class="admin__field-control">
                    <textarea rows="6"
                              name="tls-client-key"
                              required="required"
                              id="tls-client-key"
                              class="admin__control-text"></textarea>
                        <div class="admin__field-note">Key used to authenticate to the backend server.
                            Must be in PEM form, and must be accompanied by a client certificate.
                        </div>
                    </div>
                </div>
            </div>
            <div class="admin__field field">
                <label class="admin__field-label">
                    Advanced options
                </label>
            </div>

            <div class="admin__field field _required">
                <label for="maximum_connections" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Maximum connections") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="maximum_connections"
                           type="number"
                           required="required"
                           id="backend_maximum_connections"
                           class="admin__control-text
                                    required-entry
                                    validate-alphanum-with-spaces
                                    validate-length
                                    maximum-length-50"
                           value="200">
                    <div class="admin__field-note">The maximum number of connections to your backend.
                        By default, limited to 200 connections per cache node to protect origins from overload.</div>
                </div>
            </div>

            <div class="admin__field field _required">
                <label for="error_threshold" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Error threshold") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="error_threshold"
                           type="number"
                           required="required"
                           id="backend_error_threshold"
                           class="admin__control-text
                                    required-entry
                                    validate-alphanum-with-spaces
                                    validate-length
                                    maximum-length-50"
                           value="0">
                    <div class="admin__field-note">Number of errors to allow before the backend is marked as down.</div>
                </div>
            </div>

            <div class="admin__field field">
                <label class="admin__field-label">
                </label>
                <label class="admin__field-label">
                    TIMEOUTS
                </label>
            </div>

            <div class="admin__field field _required">
                <label for="connect_timeout" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Connection timeout") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="connect_timeout"
                           type="number"
                           required="required"
                           id="backend_connect_timeout"
                           class="admin__control-text
                                    required-entry
                                    validate-alphanum-with-spaces
                                    validate-length
                                    maximum-length-50"
                           value="1000">
                    <div class="admin__field-note">How long to wait for a timeout in milliseconds.</div>
                </div>
            </div>

            <div class="admin__field field _required">
                <label for="first_byte_timeout " class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("First byte timeout ") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="first_byte_timeout"
                           type="number"
                           required="required"
                           id="backend_first_byte_timeout"
                           class="admin__control-text"
                           value="15000">
                    <div class="admin__field-note">How long to wait for the first bytes in milliseconds.</div>
                </div>
            </div>

            <div class="admin__field field _required">
                <label for="between_bytes_timeout" class="admin__field-label">
                    <span><?php /* @noEscape */  echo __("Between bytes timeout") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="between_bytes_timeout"
                           type="number"
                           required="required"
                           id="backend_between_bytes_timeout"
                           class="admin__control-text"
                           value="10000">
                    <div class="admin__field-note">How long to wait between bytes in milliseconds.</div>
                </div>
            </div>

            <div class="admin__field field">
                <label for="override_host" class="admin__field-label">
                    <span><?php /* @noEscape */
                        echo __("Override host") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="override_host"
                           type="text"
                           id="override_host"
                           class="admin__control-text"
                           value="">
                    <div class="admin__field-note">Override the host header being sent to your origin regardless of the
                        host used in the initial request. Only necessary if the domain your origin is expecting is
                        different than what Fastly hosts. </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Create condition template -->
<script type="text/x-magento-template" id="fastly-create-condition-template">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field _required">
                <label for="condition_name" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="condition_name" id="condition_name" class="admin__control-text">
                </div>
            </div>

            <div class="admin__field field __required">
                <label for="apply_if" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Apply if...") ?></span>
                </label>
                <div class="admin__field-control">
                    <textarea rows="6"
                              name="apply_if"
                              required="required"
                              id="apply_if"
                              class="admin__control-text"></textarea>
                    <div class="admin__field-note">The expression to decide whether this is run.
                        Maximum length is 512 characters.
                    </div>
                </div>
            </div>

            <div class="admin__field field">
                <label for="condition_priority" class="admin__field-label">
                    <span><?php /* @noEscape */  echo __("Priority") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="condition_priority"
                           type="number"
                           required="required"
                           id="condition_priority"
                           class="admin__control-text"
                           value="10">
                    <div class="admin__field-note">For most configurations, the default (10) is best.
                        Priority determines ordering for multiple conditions. Lower numbers execute first.</div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Error page overlay template -->
<script type="text/x-magento-template" id="fastly-error-page-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-error-page-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="error_page_html" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("HTML (max 65535 characters)") ?></span>
                </label>
                <div class="admin__field-control">
                    <textarea rows="10"
                              name="error_page_html"
                              required="required"
                              id="error_page_html"
                              class="admin__control-text"></textarea>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- WAF page overlay template -->
<script type="text/x-magento-template" id="fastly-waf-page-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-waf-page-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_vcl"></label>
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="waf_page_status" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Status") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="waf_page_status" id="waf_page_status" class="admin__control-text">
                        <option value="100">100 Continue</option>
                        <option value="101">101 Switching Protocols</option>
                        <option value="102">102 Processing</option>
                        <option value="103">103 Checkpoint</option>
                        <option value="200">200 OK</option>
                        <option value="201">201 Created</option>
                        <option value="202">202 Accepted</option>
                        <option value="203">203 Non-Authoritative Information</option>
                        <option value="204">204 No Content</option>
                        <option value="205">205 Reset Content</option>
                        <option value="206">206 Partial Content</option>
                        <option value="207">207 Multi-Status</option>
                        <option value="300">300 Multiple Choices</option>
                        <option value="301">301 Moved Permanently</option>
                        <option value="302">302 Found</option>
                        <option value="303">303 See Other</option>
                        <option value="304">304 Not Modified</option>
                        <option value="305">305 Use Proxy</option>
                        <option value="306">306 Switch Proxy</option>
                        <option value="307">307 Temporary Redirect</option>
                        <option value="400">400 Bad Request</option>
                        <option value="401">401 Unauthorized</option>
                        <option value="402">402 Payment Required</option>
                        <option value="403">403 Forbidden</option>
                        <option value="404">404 Not Found</option>
                        <option value="405">405 Method Not Allowed</option>
                        <option value="406">406 Not Acceptable</option>
                        <option value="407">407 Proxy Authentication Required</option>
                        <option value="408">408 Request Timeout</option>
                        <option value="409">409 Conflict</option>
                        <option value="410">410 Gone</option>
                        <option value="411">411 Length Required</option>
                        <option value="412">412 Precondition Failed</option>
                        <option value="413">413 Request Entity Too Large</option>
                        <option value="414">414 Request-URI Too Long</option>
                        <option value="415">415 Unsupported Media Type</option>
                        <option value="416">416 Requested Range Not Satisfiable</option>
                        <option value="417">417 Expectation Failed</option>
                        <option value="418">418 I'm a teapot</option>
                        <option value="422">422 Unprocessable Entity</option>
                        <option value="423">423 Locked</option>
                        <option value="424">424 Failed Dependency</option>
                        <option value="425">425 Unordered Collection</option>
                        <option value="426">426 Upgrade Required</option>
                        <option value="449">449 Retry With</option>
                        <option value="450">450 Blocked by Windows Parental Controls</option>
                        <option value="500">500 Internal Server Error</option>
                        <option value="501">501 Not Implemented</option>
                        <option value="502">502 Bad Gateway</option>
                        <option value="503">503 Service Unavailable</option>
                        <option value="504">504 Gateway Timeout</option>
                        <option value="505">505 HTTP Version Not Supported</option>
                        <option value="506">506 Variant Also Negotiates</option>
                        <option value="507">507 Insufficient Storage</option>
                        <option value="509">509 Bandwidth Limit Exceeded</option>
                        <option value="510">510 Not Extended</option>
                    </select>
                    <div class="admin__field-note">
                        The HTTP status code to include in the header of the response.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="waf_page_type" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("MIME Type") ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="waf_page_type"
                           required="required"
                           id="waf_page_type"
                           class="admin__control-text required-entry">
                    <div class="admin__field-note">
                        The media type to put into the Content-Type header which informs the browser how to
                        display the response. Common MIME types are application/json, text/plain, text/html.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="waf_page_content" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Content (max 65535 characters)") ?></span>
                </label>
                <div class="admin__field-control">
                    <textarea rows="10"
                              name="waf_page_content"
                              required="required"
                              id="waf_page_content"
                              class="admin__control-text required-entry"></textarea>
                    <div class="admin__field-note">
                        The content to be served when delivering the response.
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Edge Dictionary creation overlay template -->
<script type="text/x-magento-template" id="fastly-dictionary-container-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="dictionary-container-form"
          class="form-inline"
          style="margin-top:25px;"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field _required">
                <label for="dictionary_name" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Dictionary name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="dictionary_name"
                           type="text"
                           required="required"
                           id="dictionary_name"
                           class="admin__control-text">
                </div>
            </div>
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Overlay template messages -->
<div class="messages">
    <div class="message message-error fastly-message-error" style="display: none; margin-bottom: 15px;"></div>
    <div class="message message-success fastly-message-success" style="display: none;"></div>
</div>

<!-- Edge Dictionary configuration overlay template -->
<script type="text/x-magento-template" id="fastly-dictionary-item-template">
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="fastly-dictionary-form"
          class="form-inline"
          enctype="multipart/form-data">
        <div class="messages">
            <div class="message message-error fastly-message-error" style="display: none; margin-bottom: 15px;"></div>
            <div class="message message-success fastly-message-success" style="display: none;"></div>
        </div>
        <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
              method="POST"
              id="fastly-dictionary-form"
              class="form-inline"
              enctype="multipart/form-data">
            <fieldset class="admin__fieldset form-list question">
                <table class="admin__control-table" id="dictionary-items-table">
                    <thead>
                    <tr>
                        <th><?php /* @noEscape */ echo __('Key') ?></th>
                        <th><?php /* @noEscape */ echo __('Value') ?></th>
                        <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Action') ?></th>
                    </tr>
                    </thead>
                    <tbody class="item-container">
                    <tr>
                        <td>
                            <input name="key"
                                   required="required"
                                   class="input-text admin__control-text dictionary-items-field"
                                   type="text">
                        </td>
                        <td>
                            <input name="value"
                                   data-type="dictionary"
                                   required="required"
                                   class="input-text admin__control-text dictionary-items-field"
                                   type="text">
                        </td>
                        <td class="col-actions">
                            <button class="action-delete fastly-save-action save_item" title="Save" type="button">
                                <span>Save</span>
                            </button>
                            <button class="action-delete remove_item"  title="Delete" type="button">
                                <span>Delete</span>
                            </button>
                        </td>
                    </tr>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="3" class="col-actions-add">
                            <button id="add-dictionary-item" class="action-add" title="Add new item" type="button">
                                <span><?php /* @noEscape */ echo __('Add new item') ?></span>
                            </button>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </fieldset>
        </form>
</script>

<!-- Edge ACL creation overlay template -->
<script type="text/x-magento-template" id="fastly-acl-container-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */  echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="acl-container-form"
          class="form-inline"
          style="margin-top:25px;"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field _required">
                <label for="acl_name" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("ACL name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="acl_name" type="text" required="required" id="acl_name" class="admin__control-text">
                </div>
            </div>
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Edge Dictionary delete overlay template -->
<script type="text/x-magento-template" id="fastly-delete-dictionary-container-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
        <div class="message message-warning" id="fastly-container-warning" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST" id="fastly-delete-dictionary-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
            <div id="delete-dictionary-container">
            </div>
        </fieldset>
    </form>
</script>

<!-- Edge ACL delete overlay template -->
<script type="text/x-magento-template" id="fastly-delete-acl-container-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
        <div class="message message-warning" id="fastly-container-warning" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST" id="fastly-delete-acl-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
            <div id="delete-acl-container">
            </div>
        </fieldset>
    </form>
</script>

<!-- Edge ACL configuration overlay template -->
<script type="text/x-magento-template" id="fastly-acl-items-template">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none; margin-bottom: 15px;"></div>
        <div class="message message-success fastly-message-success" style="display: none;"></div>
        <div class="message message-notice fastly-message-notice" >
            To add a subnet mask, use a slash ("192.0.2.0/24"). To exclude, use an exclamation mark ("!192.0.2.0").
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST" id="fastly-acl-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <table class="admin__control-table" id="acl-items-table">
                <thead>
                <tr>
                    <th><?php /* @noEscape */ echo __('Address') ?></th>
                    <th><?php /* @noEscape */ echo __('Comment (Optional)') ?></th>
                    <th><?php /* @noEscape */ echo __('Date Added') ?></th>
                    <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Action') ?></th>
                </tr>
                </thead>
                <tbody class="item-container">
                <tr>
                    <td>
                        <input name="value"
                               data-type="acl"
                               data-id=""
                               required="required"
                               class="input-text admin__control-text dictionary-items-field"
                               type="text">
                    </td>
                    <td>
                        <div class="admin__field-option" title="'+acl_negated_title+'">
                            <input name="negated"
                                   class="admin__control-checkbox"
                                   type="checkbox"
                                   id="acl_entry_'+ aclTimestamp +'">
                            <label class="admin__field-label" for="acl_entry_'+ aclTimestamp +'"></label>
                        </div>
                    </td>
                    <td class="col-actions">
                        <button class="action-delete fastly-save-action save_item" title="Save" type="button">
                            <span>Save</span>
                        </button>
                        <button class="action-delete remove_item"  title="Delete" type="button">
                            <span>Delete</span>
                        </button>
                    </td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="4" class="col-actions-add">
                        <button id="add-acl-item" class="action-add" title="Add new item" type="button">
                            <span><?php /* @noEscape */ echo __('Add new item') ?></span>
                        </button>
                    </td>
                </tr>
                </tfoot>
            </table>
        </fieldset>
    </form>
</script>

<!-- Basic Authentication creation overlay template -->
<script type="text/x-magento-template" id="fastly-auth-container-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="auth-container-form"
          class="form-inline"
          style="margin-top:25px;"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Basic Auth delete overlay template -->
<script type="text/x-magento-template" id="fastly-auth-delete-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="auth-delete-container-form"
          class="form-inline"
          style="margin-top:25px;"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Basic Authentication users overlay template -->
<script type="text/x-magento-template" id="fastly-auth-items-template">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none; margin-bottom: 15px;"></div>
        <div class="message message-success fastly-message-success" style="display: none;"></div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="fastly-auth-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <table class="admin__control-table" id="auth-items-table">
                <thead>
                <tr>
                    <th><?php /* @noEscape */ echo __('Username') ?></th>
                    <th><?php /* @noEscape */ echo __('Password') ?></th>
                    <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Action') ?></th>
                </tr>
                </thead>
                <tbody class="item-container">
                <tr>
                    <td>
                        <input name="auth_user"
                               required="required"
                               class="input-text admin__control-text auth-users-field"
                               type="text">
                    </td>
                    <td>
                        <input name="auth_pass"
                               required="required"
                               class="input-text admin__control-text auth-users-field"
                               type="text">
                    </td>
                    <td class="col-actions">
                        <button class="action-delete fastly-save-action save_item_auth" title="Save" type="button">
                            <span>Save</span>
                        </button>
                        <button class="action-delete remove_item_auth" title="Delete" type="button" hidden>
                            <span>Delete</span>
                        </button>
                    </td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="3" class="col-actions-add">
                        <button id="add-auth-item" class="action-add" title="Add new user" type="button">
                            <span><?php /* @noEscape */ echo __('Add new user') ?></span>
                        </button>
                    </td>
                </tr>
                </tfoot>
            </table>
        </fieldset>
    </form>
</script>

<!-- Image Optimization default configuration overlay template -->
<script type="text/x-magento-template" id="fastly-io-default-config-options-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("Your image configuration will be reconfigured in version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
        <div class="message message-notice fastly-message-notice">
            These settings will be used as fallbacks when no transformation rules are
            applied in the URL query string or in your VCL.
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="fastly-io-default-config-options-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_io_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate VCL after upload')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_io_vcl"
                               id="fastly_activate_io_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_io_vcl"></label>
                    </div>
                </div>
            </div>
            <table class="admin__control-table" id="io-default-config-options-table">
                <tbody class="item-container">
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Auto WebP?") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field admin__field-option">
                            <input type="radio" id="webp-no" class="admin__control-radio" name="webp-radio" value="0"/>
                            <label class="admin__field-label" for="webp-no">
                                <b>No</b> - Use the origin image file type or chosen format.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio" id="webp-yes" class="admin__control-radio" name="webp-radio" value="1"/>
                            <label class="admin__field-label" for="webp-yes">
                                <b>Yes (default)</b> - Deliver WebP images to supported browsers.
                            </label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label for="webp_quality" class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Default WebP (lossy) quality") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field field">
                            <input name="webp-quality"
                                   type="text"
                                   required="required"
                                   id="webp_quality"
                                   class="admin__control-text
                                    required-entry
                                    validate-alphanum-with-spaces
                                    validate-length
                                    maximum-length-3">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Default JPEG format") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="jpeg-format-auto"
                                   class="admin__control-radio"
                                   name="jpeg-format"
                                   value="auto"/>
                            <label class="admin__field-label" for="jpeg-format-auto">
                                <b>Auto (default)</b> - Preserve the origin image JPEG format.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="jpeg-format-baseline"
                                   class="admin__control-radio"
                                   name="jpeg-format"
                                   value="baseline"/>
                            <label class="admin__field-label" for="jpeg-format-baseline">
                                <b>Baseline</b> - Display the image when it has fully downloaded.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="jpeg-format-progressive"
                                   class="admin__control-radio"
                                   name="jpeg-format"
                                   value="progressive"/>
                            <label class="admin__field-label" for="jpeg-format-progressive">
                                <b>Progressive</b> - Display the image using low resolution first,
                                then incrementally improve the quality as downloading continues.
                            </label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label for="jpeg_quality" class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Default JPEG quality") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field field">
                            <input name="jpeg-quality"
                                   type="text"
                                   required="required"
                                   id="jpeg_quality"
                                   class="admin__control-text
                                    required-entry
                                    validate-alphanum-with-spaces
                                    validate-length
                                    maximum-length-3">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Allow upscaling?") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="upscaling-no"
                                   class="admin__control-radio"
                                   name="upscaling-radio"
                                   value="0"/>
                            <label class="admin__field-label"
                                   for="upscaling-no">
                                <b>No (default)</b> - Recommended.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="upscaling-yes"
                                   class="admin__control-radio"
                                   name="upscaling-radio"
                                   value="1"/>
                            <label class="admin__field-label" for="upscaling-yes">
                                <b>Yes</b> - Allow upscaling.
                            </label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Resize filter") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="resize-filter-lancsoz3"
                                   class="admin__control-radio"
                                   name="resize-filter-radio"
                                   value="lanczos3"/>
                            <label class="admin__field-label" for="resize-filter-lancsoz3">
                                <b>Lancsoz3 (default)</b> - Use the Lanczos3 filter to increase the
                                ability to detect edges and linear features within an image
                                and uses sinc resampling to provide the best possible reconstruction.</label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="resize-filter-lancsoz2"
                                   class="admin__control-radio"
                                   name="resize-filter-radio"
                                   value="lanczos2"/>
                            <label class="admin__field-label" for="resize-filter-lancsoz2">
                                <b>Lanczos2</b> - Use the same filter as Lancsoz3 but with
                                a less accurate approximation of the sinc resampling function.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="resize-filter-bicubic"
                                   class="admin__control-radio"
                                   name="resize-filter-radio"
                                   value="bicubic"/>
                            <label class="admin__field-label" for="resize-filter-bicubic">
                                <b>Bicubic</b> - Use an average of a 4x4 environment of pixels,
                                weighing the innermost pixels higher.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="resize-filter-bilinear"
                                   class="admin__control-radio"
                                   name="resize-filter-radio"
                                   value="bilinear"/>
                            <label class="admin__field-label" for="resize-filter-bilinear">
                                <b>Bilinear</b> - Use an average of a 2x2 environment of pixels.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="resize-filter-nearest"
                                   class="admin__control-radio"
                                   name="resize-filter-radio" value="nearest"/>
                            <label class="admin__field-label" for="resize-filter-nearest">
                                <b>Nearest</b> - Use the value of nearby translated pixel values.
                            </label>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </fieldset>
    </form>
</script>

<!-- Custom Snippet creation overlay template -->
<script type="text/x-magento-template" id="fastly-custom-snippet-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to create a custom snippet.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/createCustomSnippet'); ?>"
          method="POST"
          id="fastly-custom-snippet-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field _required">
                <label for="custom_snippet_name" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="custom_snippet_name"
                           required="required"
                           id="custom_snippet_name"
                           class="admin__control-text required-entry">
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_type" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Type") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="custom_snippet_type" id="custom_snippet_type" class="admin__control-text">
                        <option value="init">init</option>
                        <option value="recv" selected>recv</option>
                        <option value="hit">hit</option>
                        <option value="miss">miss</option>
                        <option value="pass">pass</option>
                        <option value="fetch">fetch</option>
                        <option value="error">error</option>
                        <option value="deliver">deliver</option>
                        <option value="log">log</option>
                        <option value="hash">hash</option>
                        <option value="none">none</option>
                    </select>
                    <div class="admin__field-note">
                        This specifies the location in which to place the snippet when uploaded to Fastly.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_priority" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Priority") ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="custom_snippet_priority"
                           required="required"
                           id="custom_snippet_priority"
                           value="100"
                           class="admin__control-text required-entry">
                    <div class="admin__field-note">
                        For most configurations, the default (100) is best. Priority determines the ordering for
                        multiple snippets. Lower numbers execute first.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_content" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("VCL") ?></span>
                </label>
                <div class="admin__field-control">
                    <textarea rows="10"
                              name="custom_snippet_content"
                              required="required"
                              id="custom_snippet_content"
                              class="admin__control-text required-entry"></textarea>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Custom Snippet edit overlay template -->
<script type="text/x-magento-template" id="fastly-custom-snippet-edit-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to edit a custom snippet.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/editCustomSnippet'); ?>"
          method="POST"
          id="fastly-custom-snippet-edit-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <input hidden="hidden" name="original_snippet_name" id="original_snippet_name" class="admin__control-text">
            <div class="admin__field field _required">
                <label for="custom_snippet_name" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="custom_snippet_name"
                           required="required"
                           id="custom_snippet_name"
                           class="admin__control-text required-entry">
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_type" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Type") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="custom_snippet_type" id="custom_snippet_type" class="admin__control-text">
                        <option value="init">init</option>
                        <option value="recv" selected>recv</option>
                        <option value="hit">hit</option>
                        <option value="miss">miss</option>
                        <option value="pass">pass</option>
                        <option value="fetch">fetch</option>
                        <option value="error">error</option>
                        <option value="deliver">deliver</option>
                        <option value="log">log</option>
                        <option value="hash">hash</option>
                        <option value="none">none</option>
                    </select>
                    <div class="admin__field-note">
                        This specifies the location in which to place the snippet when uploaded to Fastly.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_priority" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Priority") ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="custom_snippet_priority"
                           required="required"
                           id="custom_snippet_priority"
                           value="100"
                           class="admin__control-text required-entry">
                    <div class="admin__field-note">
                        For most configurations, the default (100) is best. Priority determines the ordering for
                        multiple snippets. Lower numbers execute first.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_content" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("VCL") ?></span>
                </label>
                <div class="admin__field-control">
                    <textarea rows="10"
                              name="custom_snippet_content"
                              required="required"
                              id="custom_snippet_content"
                              class="admin__control-text required-entry"></textarea>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Modly active module overlay template -->
<script type="text/x-magento-template" id="modly-active-module-template">
    <div class="messages module-messages">
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/setActiveModuleConfig'); ?>"
          method="POST"
          id="fastly-active-module-config-form"
          class="form-inline"
          enctype="multipart/form-data"
          style="margin-top: 25px;">
        <fieldset class="admin__fieldset form-list question">
            <input hidden="hidden" name="module_name" id="module-id" class="admin__control-text">
        </fieldset>
    </form>
</script>

<!-- Modly all modules template -->
<script type="text/x-magento-template" id="modly-all-modules-template">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
        <div class="message message-success fastly-message-success" style="display: none">
        </div>
        <div class="message message-warning fastly-message-warning" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/setActiveModules'); ?>"
          method="POST"
          id="modly-all-modules-form"
          class="form-inline"
          enctype="multipart/form-data"
          style="margin-top: 25px;">
        <fieldset class="admin__fieldset form-list question">
            <table class="admin__control-table" id="modly-all-modules-table">
                <thead>
                <tr>
                    <th><?php /* @noEscape */ echo __('Module') ?></th>
                    <th><?php /* @noEscape */ echo __('Description') ?></th>
                    <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Enabled') ?></th>
                </tr>
                </thead>
                <tbody class="item-container">
                </tbody>
            </table>
        </fieldset>
    </form>
</script>

<!-- Rate Limiting paths template -->
<script type="text/x-magento-template" id="fastly-rate-limiting-paths-template">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
        <div class="message message-success fastly-message-success" style="display: none">
        </div>
        <div class="message message-warning fastly-message-warning" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/setActiveModules'); ?>"
          method="POST"
          id="fastly-rate-limiting-form"
          class="form-inline"
          enctype="multipart/form-data"
          style="margin-top: 25px;">
        <fieldset class="admin__fieldset form-list question">
            <table class="admin__control-table" id="fastly-rate-limiting-table">
                <thead>
                <tr>
                    <th><?php /* @noEscape */ echo __('Path (regular expression)') ?></th>
                    <th><?php /* @noEscape */ echo __('Comment (optional)') ?></th>
                    <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Action') ?></th>
                </tr>
                </thead>
                <tbody class="item-container">
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="3" class="col-actions-add">
                        <button id="add-path" class="action-add" title="Add new path" type="button">
                            <span><?php /* @noEscape */ echo __('Add new path') ?></span>
                        </button>
                    </td>
                </tr>
                </tfoot>
            </table>
        </fieldset>
    </form>
</script>

<!-- Rate Limiting toggle template -->
<script type="text/x-magento-template" id="fastly-rate-limiting-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_rate_limiting"
                               id="fastly_activate_rate_limiting"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_rate_limiting"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Domains overlay template -->
<script type="text/x-magento-template" id="fastly-domains-list-template">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none; margin-bottom: 15px;"></div>
        <div class="message message-success fastly-message-success" style="display: none;"></div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="fastly-domains-list-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <table class="admin__control-table" id="domains-list-table">
                <thead>
                <tr>
                    <th><?php /* @noEscape */ echo __('Name') ?></th>
                    <th><?php /* @noEscape */ echo __('Comment') ?></th>
                    <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Action') ?></th>
                </tr>
                </thead>
                <tbody class="item-container">
                <tr>
                    <td>
                        <input name="domain_name"
                               required="required"
                               class="input-text admin__control-text domains-list-field"
                               type="text">
                    </td>
                    <td>
                        <input name="domain_comment"
                               required="required"
                               class="input-text admin__control-text domains-list-field"
                               type="text">
                    </td>
                    <td class="col-actions">
                        <button class="action-delete remove_domain" title="Delete" type="button" hidden>
                            <span>Delete</span>
                        </button>
                    </td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="3" class="col-actions-add">
                        <button id="add-domain" class="action-add" title="Add new domain" type="button">
                            <span><?php /* @noEscape */ echo __('Add Domain') ?></span>
                        </button>
                    </td>
                </tr>
                </tfoot>
            </table>
        </fieldset>
    </form>
</script>

<!-- Super Users template -->
<script type="text/x-magento-template" id="fastly-su-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll upload your VCL to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="fastly-su-form"
          class="form-inline"
          enctype="multipart/form-data">
    </form>
</script>

<!-- Export template -->
<script type="text/x-magento-template" id="fastly-export-template">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_ImportExport/downloadExportData'); ?>"
          method="POST"
          id="fastly-export-form"
          class="form-inline"
          enctype="multipart/form-data">
        <input name="form_key" type="hidden" value="<?php /* @noEscape */ echo $block->getFormKey() ?>" />
        <fieldset class="admin__fieldset form-list question">
        </fieldset>
    </form>
</script>

<script type="text/x-magento-template" id="fastly-version-history-template">
    <!-- Overlay template messages -->
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none; margin-bottom: 15px;"></div>
        <div class="message message-success fastly-message-success" style="display: none;"></div>
    </div>
    <div class="admin__fieldset recommended">
        <div class="admin__field-control">
            <div class="admin__data-grid-pager">
                <span id="pagination-active-version" style="margin-right: 2rem;"></span>
                <button class="action-previous" type="button"  title="Previous Page"></button>
                <input class="admin__control-text" id="pagination-input" type="number" value="">
                <label class="admin__control-support-text"></label>
                <button class="action-next" type="button" title="Next Page"></button>
            </div>
            <table class="admin__control-table" id="versions-list-table">
                <thead>
                    <tr>
                        <th><?php /* @noEscape */ echo __('Version Number') ?></th>
                        <th><?php /* @noEscape */ echo __('Comment') ?></th>
                        <th><?php /* @noEscape */ echo __('Updated Time') ?></th>
                        <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Action') ?></th>
                    </tr>
                </thead>
                <tbody class="item-container">
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4" class="col-actions-add"></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</script>

<script type="text/x-magento-template" id="show-VCL-container">
    <div class="admin__fieldset recommended">
        <div class="admin__field-control">
            <textarea rows="200"
                      id="version-vcl-container"
                      class="admin__control-text"></textarea>
        </div>
    </div>
</script>

<script type="text/x-magento-template" id="fastly-dismiss-vcl-warning-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to dismiss outdated VCL for current version.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_dismiss_vcl_warning" class="admin__field-label">
                    <span>
                        <?php
                        /* @noEscape */ echo __('You are about to dismiss warning for'
                                                . 'outdated VCL for current version.')
                        ?>
                    </span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_dismiss_vcl_warning"
                               id="fastly_dismiss_vcl_warning"
                               checked/>
                        <label class="admin__field-label" for="fastly_dismiss_vcl_warning"></label>
                    </div>
                </div>
            </div>
        </fieldset>
</script>
<?php

/**
 * AJAX urls passed to uploadvcl.js file
 */
// Versioning
$allFastlyVersions =            $block->getUrl('adminhtml/fastlyCdn_VersionHistory/ListVersions');
$activateVersion =              $block->getUrl('adminhtml/fastlyCdn_VersionHistory/Activate');
$versionReference =             $block->getUrl('adminhtml/fastlyCdn_VersionHistory/Reference');

// Advanced
$checkTlsSettingUrl =           $block->getUrl('adminhtml/fastlyCdn_Advanced/checkTlsSetting');
$toggleTlsSettingUrl =          $block->getUrl('adminhtml/fastlyCdn_Advanced/forceTls');
// Backend
$configureBackendUrl =          $block->getUrl('adminhtml/fastlyCdn_Backend/configureBackend');
$fetchBackendsUrl =             $block->getUrl('adminhtml/fastlyCdn_Backend/getBackends');
$createBackendUrl =             $block->getUrl('adminhtml/fastlyCdn_Backend/createBackend');
// Basic Authentication
$createAuthItem =               $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication_Item/create');
$deleteAuthItem =               $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication_Item/delete');
$getAuthItems =                 $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication_Item/listAll');
$checkAuthDictionaryUrl =       $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/checkAuthDictionary');
$checkAuthSettingUrl =          $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/checkAuthSetting');
$checkAuthUsersAvailable =      $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/checkAuthUsersAvailable');
$createAuth =                   $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/create');
$deleteAuth =                   $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/delete');
$toggleAuthSettingUrl =         $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/enableAuth');
// Blocking
$toggleBlockingSettingUrl =     $block->getUrl('adminhtml/fastlyCdn_Blocking/blocking');
$checkBlockingSettingUrl =      $block->getUrl('adminhtml/fastlyCdn_Blocking/checkBlockingSetting');
$updateBlockingUrl =            $block->getUrl('adminhtml/fastlyCdn_Blocking/updateBlocking');
// Configuration
$isFastlyEnabled =              $block->getConfig()->isFastlyEnabled();
$serviceInfoUrl =               $block->getUrl('adminhtml/fastlyCdn_Configuration/serviceInfo');
$testServiceUrl =               $block->getUrl('adminhtml/fastlyCdn_Configuration/testConnection');
$isAlreadyConfiguredUrl =       $block->getUrl('adminhtml/fastlyCdn_Configuration/isAlreadyConfigured');
$getFastlyServiceInfoUrl =      $block->getUrl('adminhtml/fastlyCdn_Configuration/getFastlyServiceInfo');
// Custom Snippet
$createCustomSnippetUrl =       $block->getUrl('adminhtml/fastlyCdn_CustomSnippet/createCustomSnippet');
$deleteCustomSnippet =          $block->getUrl('adminhtml/fastlyCdn_CustomSnippet/deleteCustomSnippet');
$getCustomSnippetsUrl =         $block->getUrl('adminhtml/fastlyCdn_CustomSnippet/getCustomSnippets');
$getCustomSnippet =             $block->getUrl('adminhtml/fastlyCdn_CustomSnippet/getCustomSnippet');
$checkCustomSnippet =           $block->getUrl('adminhtml/fastlyCdn_CustomSnippet/checkCustomSnippet');
$changeUpdateFlag =             $block->getUrl('adminhtml/fastlyCdn_CustomSnippet/changeUpdateFlag');
// Domains
$getDomainsUrl =                $block->getUrl('adminhtml/fastlyCdn_Domains/getDomains');
$pushDomainsUrl =               $block->getUrl('adminhtml/fastlyCdn_Domains/pushDomains');
// Edge ACL
$createAcl =                    $block->getUrl('adminhtml/fastlyCdn_Edge_Acl/create');
$deleteAcl =                    $block->getUrl('adminhtml/fastlyCdn_Edge_Acl/delete');
$listAcls =                     $block->getUrl('adminhtml/fastlyCdn_Edge_Acl/listAll');
$aclItems =                     $block->getUrl('adminhtml/fastlyCdn_Edge_Acl_Item/listAll');
$createAclItem =                $block->getUrl('adminhtml/fastlyCdn_Edge_Acl_Item/create');
$deleteAclItem =                $block->getUrl('adminhtml/fastlyCdn_Edge_Acl_Item/delete');
$updateAclItem =                $block->getUrl('adminhtml/fastlyCdn_Edge_Acl_Item/update');
// Edge Dictionary
$createDictionary =             $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary/create');
$deleteDictionary =             $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary/delete');
$listDictionaries =             $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary/listAll');
$dictionaryItems =              $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary_Item/listAll');
$createDictionaryItem =         $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary_Item/create');
$deleteDictionaryItem =         $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary_Item/delete');
// Image Optimization
$checkImageSettingUrl =         $block->getUrl('adminhtml/fastlyCdn_ImageOptimization/checkImageSetting');
$checkFastlyIoSettingUrl =      $block->getUrl('adminhtml/fastlyCdn_ImageOptimization/checkFastlyIoSetting');
$toggleImageSettingUrl =        $block->getUrl('adminhtml/fastlyCdn_ImageOptimization/pushImageSettings');
$listIoDefaultConfigOptions =   $block->getUrl('adminhtml/fastlyCdn_ImageOptimization/listAll');
$configureIoUrl =               $block->getUrl('adminhtml/fastlyCdn_ImageOptimization/ioDefaultConfigOptions');
$isIoEnabled =                  $block->getConfig()->isImageOptimizationEnabled();
// Import Export
$getExportDataUrl =             $block->getUrl('adminhtml/fastlyCdn_ImportExport/getExportData');
$exportDataUrl =                $block->getUrl('adminhtml/fastlyCdn_ImportExport/saveExportData');
// Maintenance Support
$checkSuSettingUrl =            $block->getUrl('adminhtml/fastlyCdn_Maintenance/CheckSuSetting');
$toggleSuSettingUrl =           $block->getUrl('adminhtml/fastlyCdn_Maintenance/toggleSuSetting');
$updateSuIpsUrl =               $block->getUrl('adminhtml/fastlyCdn_Maintenance/updateSuIps');
// Manifest
$createManifestsUrl =           $block->getUrl('adminhtml/fastlyCdn_Manifest/Create');
$toggleModulesUrl =             $block->getUrl('adminhtml/fastlyCdn_Manifest/ToggleModules');
$getAllModulesUrl =             $block->getUrl('adminhtml/fastlyCdn_Manifest/getAllModules');
$saveModuleConfigUrl =          $block->getUrl('adminhtml/fastlyCdn_Manifest/save');
$getActiveModulesUrl =          $block->getUrl('adminhtml/fastlyCdn_Manifest/getActiveModules');
$getModuleDataUrl =             $block->getUrl('adminhtml/fastlyCdn_Manifest/getModuleData');
$getAllConditionsUrl =          $block->getUrl('adminhtml/fastlyCdn_Manifest/getAllConditions');
$getAllDomainsUrl =             $block->getUrl('adminhtml/fastlyCdn_Manifest/getAllDomains');
$getCountriesUrl =              $block->getUrl('adminhtml/fastlyCdn_Manifest/getCountries');
$uploadModuleSnippetUrl =       $block->getUrl('adminhtml/fastlyCdn_Manifest/upload');
// Rate Limiting
$getPathsUrl =                  $block->getUrl('adminhtml/fastlyCdn_RateLimiting/getPaths');
$toggleRateLimitingUrl =        $block->getUrl('adminhtml/fastlyCdn_RateLimiting/toggleRateLimiting');
$updatePathsUrl =               $block->getUrl('adminhtml/fastlyCdn_RateLimiting/updatePaths');
$checkRateLimitingSettingUrl =  $block->getUrl('adminhtml/fastlyCdn_RateLimiting/checkRateLimitingSetting');
// Synthetic Pages
$getErrorPageRespObjUrl =       $block->getUrl('adminhtml/fastlyCdn_SyntheticPages/getErrorPageRespObj');
$getWafPageRespObjUrl =         $block->getUrl('adminhtml/fastlyCdn_SyntheticPages/getWafPageRespObj');
$savePageErrorHtml =            $block->getUrl('adminhtml/fastlyCdn_SyntheticPages/saveErrorPageHtml');
$saveWafPage =                  $block->getUrl('adminhtml/fastlyCdn_SyntheticPages/saveWafPage');
// VCL
$vclUploadUrl =                 $block->getUrl('adminhtml/fastlyCdn_Vcl/upload');
$dismissWarning =               $block->getUrl('adminhtml/fastlyCdn_Vcl/dismissWarning');
$vclComparison =                $block->getUrl('adminhtml/fastlyCdn_Vcl/comparison');
$isWarningDismissed =           $block->getUrl('adminhtml/fastlyCdn_Vcl/isWarningDismissed');
$getUpdateFlag =            $block->getUrl('adminhtml/fastlyCdn_Vcl/getUpdateFlag');
// Web Application Firewall
$getWafSettingsUrl =            $block->getUrl('adminhtml/fastlyCdn_Waf/getWafSettings');
$getOwaspSettingsUrl =          $block->getUrl('adminhtml/fastlyCdn_Waf/getOwaspSettings');
$toggleWafBypassSettingUrl =    $block->getUrl('adminhtml/fastlyCdn_Waf/wafAllowlist');
$checkWafBypassSettingUrl =     $block->getUrl('adminhtml/fastlyCdn_Waf/checkWafBypassSetting');
$updateWafBypassUrl =           $block->getUrl('adminhtml/fastlyCdn_Waf/updateWafAllowlist');

// This flag is used to prevent calling ajax requests if fastly extension is not selected as caching application
$isFastlyEnabled =              $block->getConfig()->isFastlyEnabled();
?>

<script type="text/x-magento-init">
        {
            "*": {
                "Fastly_Cdn/js/init": {
                    "serviceInfoUrl": "<?php echo $block->escapeJsQuote($serviceInfoUrl);?>",
                    "vclUploadUrl": "<?php echo $block->escapeJsQuote($vclUploadUrl);?>",
                    "testServiceUrl": "<?php echo $block->escapeJsQuote($testServiceUrl);?>",
                    "checkTlsSettingUrl": "<?php echo $block->escapeJsQuote($checkTlsSettingUrl);?>",
                    "toggleTlsSettingUrl": "<?php echo $block->escapeJsQuote($toggleTlsSettingUrl);?>",
                    "checkImageSettingUrl": "<?php echo $block->escapeJsQuote($checkImageSettingUrl);?>",
                    "checkFastlyIoSettingUrl": "<?php echo $block->escapeJsQuote($checkFastlyIoSettingUrl);?>",
                    "toggleImageSettingUrl": "<?php echo $block->escapeJsQuote($toggleImageSettingUrl);?>",
                    "checkBlockingSettingUrl": "<?php echo $block->escapeJsQuote($checkBlockingSettingUrl);?>",
                    "toggleBlockingSettingUrl": "<?php echo $block->escapeJsQuote($toggleBlockingSettingUrl);?>",
                    "isFastlyEnabled": "<?php echo $block->escapeJsQuote($isFastlyEnabled);?>",
                    "isIoEnabled": "<?php echo $block->escapeJsQuote($isIoEnabled);?>",
                    "fetchBackendsUrl": "<?php echo $block->escapeJsQuote($fetchBackendsUrl);?>",
                    "configureBackendUrl": "<?php echo $block->escapeJsQuote($configureBackendUrl);?>",
                    "isAlreadyConfiguredUrl": "<?php echo $block->escapeJsQuote($isAlreadyConfiguredUrl);?>",
                    "saveErrorPageHtmlUrl": "<?php echo $block->escapeJsQuote($savePageErrorHtml);?>",
                    "saveWafPageUrl": "<?php echo $block->escapeJsQuote($saveWafPage);?>",
                    "getErrorPageRespObj": "<?php echo $block->escapeJsQuote($getErrorPageRespObjUrl);?>",
                    "getWafPageRespObj": "<?php echo $block->escapeJsQuote($getWafPageRespObjUrl);?>",
                    "createDictionary": "<?php echo $block->escapeJsQuote($createDictionary);?>",
                    "deleteDictionary": "<?php echo $block->escapeJsQuote($deleteDictionary);?>",
                    "getDictionaries": "<?php echo $block->escapeJsQuote($listDictionaries);?>",
                    "getDictionaryItems": "<?php echo $block->escapeJsQuote($dictionaryItems);?>",
                    "createDictionaryItem": "<?php echo $block->escapeJsQuote($createDictionaryItem);?>",
                    "deleteDictionaryItem": "<?php echo $block->escapeJsQuote($deleteDictionaryItem);?>",
                    "createAcl": "<?php echo $block->escapeJsQuote($createAcl);?>",
                    "deleteAcl": "<?php echo $block->escapeJsQuote($deleteAcl);?>",
                    "deleteCustomSnippet": "<?php echo $block->escapeJsQuote($deleteCustomSnippet);?>",
                    "getCustomSnippet": "<?php echo $block->escapeJsQuote($getCustomSnippet);?>",
                    "checkCustomSnippet": "<?php echo $block->escapeJsQuote($checkCustomSnippet);?>",
                    "getAcls": "<?php echo $block->escapeJsQuote($listAcls);?>",
                    "getAclItems": "<?php echo $block->escapeJsQuote($aclItems);?>",
                    "createAclItem": "<?php echo $block->escapeJsQuote($createAclItem);?>",
                    "deleteAclItem": "<?php echo $block->escapeJsQuote($deleteAclItem);?>",
                    "updateAclItem": "<?php echo $block->escapeJsQuote($updateAclItem);?>",
                    "getAuths": "<?php echo $block->escapeJsQuote($getAuthItems);?>",
                    "createAuth": "<?php echo $block->escapeJsQuote($createAuth);?>",
                    "deleteAuth": "<?php echo $block->escapeJsQuote($deleteAuth);?>",
                    "createAuthItem": "<?php echo $block->escapeJsQuote($createAuthItem);?>",
                    "deleteAuthItem": "<?php echo $block->escapeJsQuote($deleteAuthItem);?>",
                    "checkAuthSettingUrl": "<?php echo $block->escapeJsQuote($checkAuthSettingUrl);?>",
                    "checkAuthDictionaryUrl": "<?php echo $block->escapeJsQuote($checkAuthDictionaryUrl);?>",
                    "toggleAuthSettingUrl": "<?php echo $block->escapeJsQuote($toggleAuthSettingUrl);?>",
                    "checkAuthUsersAvailable": "<?php echo $block->escapeJsQuote($checkAuthUsersAvailable);?>",
                    "listIoDefaultConfigOptions": "<?php echo $block->escapeJsQuote($listIoDefaultConfigOptions);?>",
                    "toggleModulesUrl": "<?php echo $block->escapeJsQuote($toggleModulesUrl);?>",
                    "configureIoUrl": "<?php echo $block->escapeJsQuote($configureIoUrl);?>",
                    "createCustomSnippetUrl": "<?php echo $block->escapeJsQuote($createCustomSnippetUrl);?>",
                    "getCustomSnippetsUrl": "<?php echo $block->escapeJsQuote($getCustomSnippetsUrl);?>",
                    "createManifestsUrl": "<?php echo $block->escapeJsQuote($createManifestsUrl);?>",
                    "getAllModulesUrl": "<?php echo $block->escapeJsQuote($getAllModulesUrl);?>",
                    "saveModuleConfigUrl": "<?php echo $block->escapeJsQuote($saveModuleConfigUrl);?>",
                    "getActiveModulesUrl": "<?php echo $block->escapeJsQuote($getActiveModulesUrl);?>",
                    "getModuleDataUrl": "<?php echo $block->escapeJsQuote($getModuleDataUrl);?>",
                    "getAllConditionsUrl": "<?php echo $block->escapeJsQuote($getAllConditionsUrl);?>",
                    "getAllDomainsUrl": "<?php echo $block->escapeJsQuote($getAllDomainsUrl);?>",
                    "getCountriesUrl": "<?php echo $block->escapeJsQuote($getCountriesUrl);?>",
                    "uploadModuleSnippetUrl": "<?php echo $block->escapeJsQuote($uploadModuleSnippetUrl);?>",
                    "updateBlockingUrl": "<?php echo $block->escapeJsQuote($updateBlockingUrl);?>",
                    "getFastlyServiceInfoUrl": "<?php echo $block->escapeJsQuote($getFastlyServiceInfoUrl);?>",
                    "getWafSettingsUrl": "<?php echo $block->escapeJsQuote($getWafSettingsUrl);?>",
                    "getOwaspSettingsUrl": "<?php echo $block->escapeJsQuote($getOwaspSettingsUrl);?>",
                    "toggleWafBypassSettingUrl": "<?php echo $block->escapeJsQuote($toggleWafBypassSettingUrl);?>",
                    "checkWafBypassSettingUrl": "<?php echo $block->escapeJsQuote($checkWafBypassSettingUrl);?>",
                    "updateWafBypassUrl": "<?php echo $block->escapeJsQuote($updateWafBypassUrl);?>",
                    "getDomainsUrl": "<?php echo $block->escapeJsQuote($getDomainsUrl);?>",
                    "pushDomainsUrl": "<?php echo $block->escapeJsQuote($pushDomainsUrl);?>",
                    "getPathsUrl": "<?php echo $block->escapeJsQuote($getPathsUrl);?>",
                    "toggleRateLimitingUrl": "<?php echo $block->escapeJsQuote($toggleRateLimitingUrl);?>",
                    "updatePathsUrl": "<?php echo $block->escapeJsQuote($updatePathsUrl);?>",
                    "checkRateLimitingSettingUrl": "<?php echo $block->escapeJsQuote($checkRateLimitingSettingUrl);?>",
                    "checkSuSettingUrl": "<?php echo $block->escapeJsQuote($checkSuSettingUrl);?>",
                    "toggleSuSettingUrl": "<?php echo $block->escapeJsQuote($toggleSuSettingUrl);?>",
                    "updateSuIpsUrl": "<?php echo $block->escapeJsQuote($updateSuIpsUrl);?>",
                    "createBackendUrl": "<?php echo $block->escapeJsQuote($createBackendUrl);?>",
                    "getExportDataUrl": "<?php echo $block->escapeJsQuote($getExportDataUrl);?>",
                    "exportDataUrl": "<?php echo $block->escapeJsQuote($exportDataUrl);?>",
                    "versionHistory": "<?php echo $block->escapeJsQuote($allFastlyVersions);?>",
                    "activateVersion": "<?php echo $block->escapeJsQuote($activateVersion); ?>",
                    "versionReference": "<?php echo $block->escapeJsQuote($versionReference); ?>",
                    "vclComparison": "<?php echo $block->escapeJsQuote($vclComparison); ?>",
                    "dismissWarning": "<?php echo $block->escapeJsQuote($dismissWarning); ?>",
                    "isWarningDismissed": "<?php echo $block->escapeJsQuote($isWarningDismissed); ?>",
                    "getUpdateFlag": "<?php echo $block->escapeJsQuote($getUpdateFlag); ?>",
                    "changeUpdateFlag": "<?php echo $block->escapeJsQuote($changeUpdateFlag); ?>"
                }
            }
        }
</script>

<style type="text/css">
    #backend-upload-form {
        margin-top: 25px;
    }

    .dictionary-items-field {
        width: 100%;
    }

    .highlighted > td{
        background: #fffbbb;
    }

    .fastly-dismiss-warning-action::before {
        content: '\e620';
        font-size: 2rem;
    }

    .admin__control-table .fastly-save-action::before {
        content: '\1F4BE';
        font-size: 2rem;
    }

    .admin__control-table .fastly-edit-action::before {
        content: '\e610';
        font-size: 2rem;
    }

    .admin__control-table .fastly-activate-vcl-action {
        background-image: url("<?php /* @noEscape */ echo $block->getViewFileUrl('Fastly_Cdn::images/cloud.svg') ?>");
        width: 2.5rem;
        height: 2.5rem;
        background-color: transparent;
        border-color: transparent;
        box-shadow: none;
        padding-left: 0;
        padding-right: 0;
        background-repeat: no-repeat;
    }

    .admin__control-table .fastly-view-vcl-action {
        background-image: url("<?php /* @noEscape */ echo $block->getViewFileUrl('Fastly_Cdn::images/view.svg') ?>");
        width: 2.5rem;
        height: 2.5rem;
        background-color: transparent;
        border-color: transparent;
        box-shadow: none;
        padding-left: 0;
        padding-right: 0;
        background-repeat: no-repeat;
    }

    .dialog-item {
        border: none;
        background-color: transparent;
    }

    #attach_span {
        line-height: 3.2rem;
        white-space: nowrap;
    }

    .checkbox-input {
        margin-bottom: 5px;
    }

    .recommended {
        border: 1px solid #D8D8D8;
        border-radius: 3px;
        margin-bottom: 30px;
    }

    #recommended-title {
        margin-bottom: 10px;
    }

    .message-recommend {
        border: 1px solid #FEDF69;
        background-color: #FFF9D5;
        padding-top: 10px;
        margin-bottom: 30px;
    }

</style>

