<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!-- Upload VCL overlay template -->
<script type="text/x-magento-template" id="fastly-uploadvcl-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll upload your VCL to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate VCL after upload')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_vcl"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Force TLS toggle overlay template -->
<script type="text/x-magento-template" id="fastly-tls-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_tls"
                               id="fastly_activate_tls"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Image Optimization toggle overlay template -->
<script type="text/x-magento-template" id="fastly-image-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-warning" id="fastly-image-template-notifications" style="display: none"></div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl"
                       class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span></label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_image_vcl"
                               id="fastly_activate_image_vcl" checked/>
                        <label class="admin__field-label" for="fastly_activate_image_vcl"></label>
                    </div>
                </div>
            </div>
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_image_quality_flag"
                       class="admin__field-label">
                    <span>
                        <?php /* @noEscape */ echo __('Set image quality to Magento default')?>
                    </span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_image_quality_flag"
                               id="fastly_image_quality_flag"/>
                        <label class="admin__field-label" for="fastly_image_quality_flag"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Blocking toggle overlay template -->
<script type="text/x-magento-template" id="fastly-blocking-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_blocking"
                               id="fastly_activate_blocking"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_blocking"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Basic Authentication toggle overlay template -->
<script type="text/x-magento-template" id="fastly-auth-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error"
             id="fastly-auth-toggle-message-error"
             style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_auth"
                               id="fastly_activate_auth"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_auth"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Backend configuration overlay template -->
<script type="text/x-magento-template" id="fastly-backend-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("Your backend will be reconfigured in version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="backend-upload-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <input hidden="hidden" name="backend_name" id="backend_name" class="admin__control-text">
            <div class="admin__field field">
                <label for="shield" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Shield") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="shield" id="backend_shield" class="admin__control-text">
                        <option value="">(none)</option>
                        <option value="fjr-ae">AE, Fujairah Al Mahta - Dubai</option>
                        <option value="brisbane-au">AU, Brisbane</option>
                        <option value="melbourne-au">AU, Melbourne</option>
                        <option value="perth-au">AU, Perth</option>
                        <option value="sydney-au">
                            AU, Sydney - Recommended for AWS ap-southeast-2, GCP australia-southeast1 origins
                        </option>
                        <option value="gru-br-sa">
                            BR, Sao Paulo - Recommended for AWS sa-east-1, GCP southamerica-east1
                        </option>
                        <option value="yyz-on-ca">CA, Toronto</option>
                        <option value="yul-montreal-ca">
                            CA, Montreal - Recommended for AWS ca-central-1, GCP northamerica-northeast1 origins
                        </option>
                        <option value="mad-madrid-es">ES, Madrid</option>
                        <option value="hel-helsinki-fi">FI, Helsinki - Recommended for GCP europe-north1</option>
                        <option value="cdg-par-fr">FR, Paris- Recommended for AWS eu-west3 and GCP e </option>
                        <option value="hongkong-hk">HK, Hong Kong</option>
                        <option value="hhn-frankfurt-de">
                            DE, Frankfurt - Interxion - Recommended for GCP europe-west3 origins
                        </option>
                        <option value="frankfurt-de">DE, Frankfurt - Recommended for AWS eu-central1 origins</option>
                        <option value="tokyo-jp2">JP, Tokyo - Recommended for AWS ap-northeast-1 origins</option>
                        <option value="osaka-jp">JP, Osaka - Recommened for AWS ap-northeast-3 origins</option>
                        <option value="amsterdam-nl">NL, Amsterdam - Recommended for GCP eu-west1/4 origins</option>
                        <option value="auckland-akl">NZ, Auckland</option>
                        <option value="wellington-wlg">NZ, Wellington</option>
                        <option value="stockholm-bma">SE, Stockholm</option>
                        <option value="singapore-sg">
                            SG, Singapore - Recommended for AWS ap-southeast-1, GCP asia-southeast1 origins
                        </option>
                        <option value="london_city-uk">
                            UK, London - LCY - Recommended for AWS eu-west1/2 origins
                        </option>
                        <option value="london-uk">UK, London - LHR - Recommended for GCP eu-west2 origins</option>
                        <option value="atl-ga-us">US, Atlanta, GA</option>
                        <option value="bos-ma-us">US, Boston, MA</option>
                        <option value="mdw-il-us">US, Chicago, IL - Recommended for GCP us-central1 origins</option>
                        <option value="den-co-us">US, Denver, CO</option>
                        <option value="dallas-tx-us">US, Dallas, TX</option>
                        <option value="iax-tx-us">US, Houston, TX</option>
                        <option value="iad-va-us">
                            US, Washington, DC - Recommended for AWS us-east1, GCP us-east1/4 origins
                        </option>
                        <option value="lax-ca-us">US, Los Angeles, CA - Recommended for GCP us-west2</option>
                        <option value="miami-fl-us">US, Miami, FL</option>
                        <option value="jfk-ny-us">US, New York City, NY</option>
                        <option value="sjc-ca-us">US, San Jose, CA</option>
                        <option value="sea-wa-us">
                            US, Seattle, WA - Recommended for AWS us-west2, GCP us-west1 origins
                        </option>
                        <option value="cpt-capetown-za">ZA, Capetown</option>
                        <option value="jnb-johannesburg-za">ZA, Johannesburg</option>
                    </select>
                    <div class="admin__field-note">
                        The shield POP designated to reduce inbound load on this origin by serving the cached data to
                        the rest of the network.
                        <a href="https://docs.fastly.com/guides/performance-tuning/shielding"
                           target="_blank">Click for more details.</a>
                    </div>
                </div>
            </div>

            <div class="admin__field field _required">
                <label for="connect_timeout" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Connect timeout") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="connect_timeout"
                           type="number"
                           required="required"
                           id="backend_connect_timeout"
                           class="admin__control-text
                                    required-entry
                                    validate-alphanum-with-spaces
                                    validate-length
                                    maximum-length-50">
                    <div class="admin__field-note">How long to wait for a timeout in milliseconds.</div>
                </div>
            </div>

            <div class="admin__field field _required">
                <label for="between_bytes_timeout" class="admin__field-label">
                    <span><?php /* @noEscape */  echo __("Between bytes timeout") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="between_bytes_timeout"
                           type="number"
                           required="required"
                           id="backend_between_bytes_timeout"
                           class="admin__control-text">
                    <div class="admin__field-note">How long to wait between bytes in milliseconds.</div>
                </div>
            </div>

            <div class="admin__field field _required">
                <label for="first_byte_timeout " class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("First byte timeout ") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="first_byte_timeout"
                           type="number"
                           required="required"
                           id="backend_first_byte_timeout"
                           class="admin__control-text">
                    <div class="admin__field-note">How long to wait for the first bytes in milliseconds.</div>
                </div>
            </div>

            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_backend" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_backend"
                               id="fastly_activate_backend"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_backend"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Error page overlay template -->
<script type="text/x-magento-template" id="fastly-error-page-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-error-page-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="error_page_html" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("HTML (max 65535 characters)") ?></span>
                </label>
                <div class="admin__field-control">
                    <textarea rows="10"
                              name="error_page_html"
                              required="required"
                              id="error_page_html"
                              class="admin__control-text"></textarea>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- WAF page overlay template -->
<script type="text/x-magento-template" id="fastly-waf-page-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="vcl-waf-page-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_vcl"></label>
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="waf_page_status" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Status") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="waf_page_status" id="waf_page_status" class="admin__control-text">
                        <option value="100">100 Continue</option>
                        <option value="101">101 Switching Protocols</option>
                        <option value="102">102 Processing</option>
                        <option value="103">103 Checkpoint</option>
                        <option value="200">200 OK</option>
                        <option value="201">201 Created</option>
                        <option value="202">202 Accepted</option>
                        <option value="203">203 Non-Authoritative Information</option>
                        <option value="204">204 No Content</option>
                        <option value="205">205 Reset Content</option>
                        <option value="206">206 Partial Content</option>
                        <option value="207">207 Multi-Status</option>
                        <option value="300">300 Multiple Choices</option>
                        <option value="301">301 Moved Permanently</option>
                        <option value="302">302 Found</option>
                        <option value="303">303 See Other</option>
                        <option value="304">304 Not Modified</option>
                        <option value="305">305 Use Proxy</option>
                        <option value="306">306 Switch Proxy</option>
                        <option value="307">307 Temporary Redirect</option>
                        <option value="400">400 Bad Request</option>
                        <option value="401">401 Unauthorized</option>
                        <option value="402">402 Payment Required</option>
                        <option value="403">403 Forbidden</option>
                        <option value="404">404 Not Found</option>
                        <option value="405">405 Method Not Allowed</option>
                        <option value="406">406 Not Acceptable</option>
                        <option value="407">407 Proxy Authentication Required</option>
                        <option value="408">408 Request Timeout</option>
                        <option value="409">409 Conflict</option>
                        <option value="410">410 Gone</option>
                        <option value="411">411 Length Required</option>
                        <option value="412">412 Precondition Failed</option>
                        <option value="413">413 Request Entity Too Large</option>
                        <option value="414">414 Request-URI Too Long</option>
                        <option value="415">415 Unsupported Media Type</option>
                        <option value="416">416 Requested Range Not Satisfiable</option>
                        <option value="417">417 Expectation Failed</option>
                        <option value="418">418 I'm a teapot</option>
                        <option value="422">422 Unprocessable Entity</option>
                        <option value="423">423 Locked</option>
                        <option value="424">424 Failed Dependency</option>
                        <option value="425">425 Unordered Collection</option>
                        <option value="426">426 Upgrade Required</option>
                        <option value="449">449 Retry With</option>
                        <option value="450">450 Blocked by Windows Parental Controls</option>
                        <option value="500">500 Internal Server Error</option>
                        <option value="501">501 Not Implemented</option>
                        <option value="502">502 Bad Gateway</option>
                        <option value="503">503 Service Unavailable</option>
                        <option value="504">504 Gateway Timeout</option>
                        <option value="505">505 HTTP Version Not Supported</option>
                        <option value="506">506 Variant Also Negotiates</option>
                        <option value="507">507 Insufficient Storage</option>
                        <option value="509">509 Bandwidth Limit Exceeded</option>
                        <option value="510">510 Not Extended</option>
                    </select>
                    <div class="admin__field-note">
                        The HTTP status code to include in the header of the response.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="waf_page_type" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("MIME Type") ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="waf_page_type"
                           required="required"
                           id="waf_page_type"
                           class="admin__control-text required-entry">
                    <div class="admin__field-note">
                        The media type to put into the Content-Type header which informs the browser how to
                        display the response. Common MIME types are application/json, text/plain, text/html.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="waf_page_content" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Content (max 65535 characters)") ?></span>
                </label>
                <div class="admin__field-control">
                    <textarea rows="10"
                              name="waf_page_content"
                              required="required"
                              id="waf_page_content"
                              class="admin__control-text required-entry"></textarea>
                    <div class="admin__field-note">
                        The content to be served when delivering the response.
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Edge Dictionary creation overlay template -->
<script type="text/x-magento-template" id="fastly-dictionary-container-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="dictionary-container-form"
          class="form-inline"
          style="margin-top:25px;"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field _required">
                <label for="dictionary_name" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Dictionary name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="dictionary_name"
                           type="text"
                           required="required"
                           id="dictionary_name"
                           class="admin__control-text">
                </div>
            </div>
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Overlay template messages -->
<div class="messages">
    <div class="message message-error fastly-message-error" style="display: none; margin-bottom: 15px;"></div>
    <div class="message message-success fastly-message-success" style="display: none;"></div>
</div>

<!-- Edge Dictionary configuration overlay template -->
<script type="text/x-magento-template" id="fastly-dictionary-item-template">
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="fastly-dictionary-form"
          class="form-inline"
          enctype="multipart/form-data">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none; margin-bottom: 15px;"></div>
        <div class="message message-success fastly-message-success" style="display: none;"></div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="fastly-dictionary-form"
          class="form-inline"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <table class="admin__control-table" id="dictionary-items-table">
                <thead>
                <tr>
                    <th><?php /* @noEscape */ echo __('Key') ?></th>
                    <th><?php /* @noEscape */ echo __('Value') ?></th>
                    <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Action') ?></th>
                </tr>
                </thead>
                <tbody class="item-container">
                <tr>
                    <td>
                        <input name="key"
                               required="required"
                               class="input-text admin__control-text dictionary-items-field"
                               type="text">
                    </td>
                    <td>
                        <input name="value"
                               data-type="dictionary"
                               required="required"
                               class="input-text admin__control-text dictionary-items-field"
                               type="text">
                    </td>
                    <td class="col-actions">
                        <button class="action-delete fastly-save-action save_item" title="Save" type="button">
                            <span>Save</span>
                        </button>
                        <button class="action-delete remove_item"  title="Delete" type="button">
                            <span>Delete</span>
                        </button>
                    </td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="3" class="col-actions-add">
                        <button id="add-dictionary-item" class="action-add" title="Add new item" type="button">
                            <span><?php /* @noEscape */ echo __('Add new item') ?></span>
                        </button>
                    </td>
                </tr>
                </tfoot>
            </table>
        </fieldset>
    </form>
</script>

<!-- Edge ACL creation overlay template -->
<script type="text/x-magento-template" id="fastly-acl-container-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */  echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="acl-container-form"
          class="form-inline"
          style="margin-top:25px;"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field _required">
                <label for="acl_name" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("ACL name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input name="acl_name" type="text" required="required" id="acl_name" class="admin__control-text">
                </div>
            </div>
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Edge Dictionary delete overlay template -->
<script type="text/x-magento-template" id="fastly-delete-dictionary-container-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
        <div class="message message-warning" id="fastly-container-warning" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST" id="fastly-delete-dictionary-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
            <div id="delete-dictionary-container">
            </div>
        </fieldset>
    </form>
</script>

<!-- Edge ACL delete overlay template -->
<script type="text/x-magento-template" id="fastly-delete-acl-container-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
        <div class="message message-warning" id="fastly-container-warning" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST" id="fastly-delete-acl-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
            <div id="delete-acl-container">
            </div>
        </fieldset>
    </form>
</script>

<!-- Edge ACL configuration overlay template -->
<script type="text/x-magento-template" id="fastly-acl-items-template">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none; margin-bottom: 15px;"></div>
        <div class="message message-success fastly-message-success" style="display: none;"></div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST" id="fastly-acl-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <table class="admin__control-table" id="acl-items-table">
                <thead>
                <tr>
                    <th><?php /* @noEscape */ echo __('IP Value') ?></th>
                    <th><?php /* @noEscape */ echo __('Negated') ?></th>
                    <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Action') ?></th>
                </tr>
                </thead>
                <tbody class="item-container">
                <tr>
                    <td>
                        <input name="value"
                               data-type="acl"
                               data-id=""
                               required="required"
                               class="input-text admin__control-text dictionary-items-field"
                               type="text">
                    </td>
                    <td>
                        <div class="admin__field-option" title="'+acl_negated_title+'">
                            <input name="negated"
                                   class="admin__control-checkbox"
                                   type="checkbox"
                                   id="acl_entry_'+ aclTimestamp +'">
                            <label class="admin__field-label" for="acl_entry_'+ aclTimestamp +'"></label>
                        </div>
                    </td>
                    <td class="col-actions">
                        <button class="action-delete fastly-save-action save_item" title="Save" type="button">
                            <span>Save</span>
                        </button>
                        <button class="action-delete remove_item"  title="Delete" type="button">
                            <span>Delete</span>
                        </button>
                    </td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="3" class="col-actions-add">
                        <button id="add-acl-item" class="action-add" title="Add new item" type="button">
                            <span><?php /* @noEscape */ echo __('Add new item') ?></span>
                        </button>
                    </td>
                </tr>
                </tfoot>
            </table>
        </fieldset>
    </form>
</script>

<!-- Basic Authentication creation overlay template -->
<script type="text/x-magento-template" id="fastly-auth-container-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="auth-container-form"
          class="form-inline"
          style="margin-top:25px;"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Basic Auth delete overlay template -->
<script type="text/x-magento-template" id="fastly-auth-delete-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("We'll make the changes to version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="auth-delete-container-form"
          class="form-inline"
          style="margin-top:25px;"
          enctype="multipart/form-data">
        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate after the change')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_vcl"
                               id="fastly_activate_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_tls"></label>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Basic Authentication users overlay template -->
<script type="text/x-magento-template" id="fastly-auth-items-template">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none; margin-bottom: 15px;"></div>
        <div class="message message-success fastly-message-success" style="display: none;"></div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="fastly-auth-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <table class="admin__control-table" id="auth-items-table">
                <thead>
                <tr>
                    <th><?php /* @noEscape */ echo __('Username') ?></th>
                    <th><?php /* @noEscape */ echo __('Password') ?></th>
                    <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Action') ?></th>
                </tr>
                </thead>
                <tbody class="item-container">
                <tr>
                    <td>
                        <input name="auth_user"
                               required="required"
                               class="input-text admin__control-text auth-users-field"
                               type="text">
                    </td>
                    <td>
                        <input name="auth_pass"
                               required="required"
                               class="input-text admin__control-text auth-users-field"
                               type="text">
                    </td>
                    <td class="col-actions">
                        <button class="action-delete fastly-save-action save_item_auth" title="Save" type="button">
                            <span>Save</span>
                        </button>
                        <button class="action-delete remove_item_auth" title="Delete" type="button" hidden>
                            <span>Delete</span>
                        </button>
                    </td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="3" class="col-actions-add">
                        <button id="add-auth-item" class="action-add" title="Add new user" type="button">
                            <span><?php /* @noEscape */ echo __('Add new user') ?></span>
                        </button>
                    </td>
                </tr>
                </tfoot>
            </table>
        </fieldset>
    </form>
</script>

<!-- Image Optimization default configuration overlay template -->
<script type="text/x-magento-template" id="fastly-io-default-config-options-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to clone your active version #x.")?>
            <?php /* @noEscape */ echo __("Your image configuration will be reconfigured in version #y.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/upload'); ?>"
          method="POST"
          id="fastly-io-default-config-options-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field maintenance-checkbox-container">
                <label for="fastly_activate_io_vcl" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __('Activate VCL after upload')?></span>
                </label>
                <div class="admin__field-control">
                    <div class="admin__field-option">
                        <input class="admin__control-checkbox"
                               type="checkbox"
                               name="fastly_activate_io_vcl"
                               id="fastly_activate_io_vcl"
                               checked/>
                        <label class="admin__field-label" for="fastly_activate_io_vcl"></label>
                    </div>
                </div>
            </div>
            <table class="admin__control-table" id="io-default-config-options-table">
                <tbody class="item-container">
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Auto WebP?") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field admin__field-option">
                            <input type="radio" id="webp-no" class="admin__control-radio" name="webp-radio" value="0"/>
                            <label class="admin__field-label" for="webp-no">
                                <b>No</b> - Use the origin image file type or chosen format.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio" id="webp-yes" class="admin__control-radio" name="webp-radio" value="1"/>
                            <label class="admin__field-label" for="webp-yes">
                                <b>Yes (default)</b> - Deliver WebP images to supported browsers.
                            </label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label for="webp_quality" class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Default WebP (lossy) quality") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field field">
                            <input name="webp-quality"
                                   type="text"
                                   required="required"
                                   id="webp_quality"
                                   class="admin__control-text
                                    required-entry
                                    validate-alphanum-with-spaces
                                    validate-length
                                    maximum-length-3">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Default JPEG format") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="jpeg-format-auto"
                                   class="admin__control-radio"
                                   name="jpeg-format"
                                   value="auto"/>
                            <label class="admin__field-label" for="jpeg-format-auto">
                                <b>Auto (default)</b> - Preserve the origin image JPEG format.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="jpeg-format-baseline"
                                   class="admin__control-radio"
                                   name="jpeg-format"
                                   value="baseline"/>
                            <label class="admin__field-label" for="jpeg-format-baseline">
                                <b>Baseline</b> - Display the image when it has fully downloaded.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="jpeg-format-progressive"
                                   class="admin__control-radio"
                                   name="jpeg-format"
                                   value="progressive"/>
                            <label class="admin__field-label" for="jpeg-format-progressive">
                                <b>Progressive</b> - Display the image using low resolution first,
                                then incrementally improve the quality as downloading continues.
                            </label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label for="jpeg_quality" class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Default JPEG quality") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field field">
                            <input name="jpeg-quality"
                                   type="text"
                                   required="required"
                                   id="jpeg_quality"
                                   class="admin__control-text
                                    required-entry
                                    validate-alphanum-with-spaces
                                    validate-length
                                    maximum-length-3">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Allow upscaling?") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="upscaling-no"
                                   class="admin__control-radio"
                                   name="upscaling-radio"
                                   value="0"/>
                            <label class="admin__field-label"
                                   for="upscaling-no">
                                <b>No (default)</b> - Recommended.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="upscaling-yes"
                                   class="admin__control-radio"
                                   name="upscaling-radio"
                                   value="1"/>
                            <label class="admin__field-label" for="upscaling-yes">
                                <b>Yes</b> - Allow upscaling.
                            </label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="admin__field field _required">
                            <label class="admin__field-label">
                                <span><?php /* @noEscape */ echo __("Resize filter") ?></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="resize-filter-lancsoz3"
                                   class="admin__control-radio"
                                   name="resize-filter-radio"
                                   value="lanczos3"/>
                            <label class="admin__field-label" for="resize-filter-lancsoz3">
                                <b>Lancsoz3 (default)</b> - Use the Lanczos3 filter to increase the
                                ability to detect edges and linear features within an image
                                and uses sinc resampling to provide the best possible reconstruction.</label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="resize-filter-lancsoz2"
                                   class="admin__control-radio"
                                   name="resize-filter-radio"
                                   value="lanczos2"/>
                            <label class="admin__field-label" for="resize-filter-lancsoz2">
                                <b>Lanczos2</b> - Use the same filter as Lancsoz3 but with
                                a less accurate approximation of the sinc resampling function.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="resize-filter-bicubic"
                                   class="admin__control-radio"
                                   name="resize-filter-radio"
                                   value="bicubic"/>
                            <label class="admin__field-label" for="resize-filter-bicubic">
                                <b>Bicubic</b> - Use an average of a 4x4 environment of pixels,
                                weighing the innermost pixels higher.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="resize-filter-bilinear"
                                   class="admin__control-radio"
                                   name="resize-filter-radio"
                                   value="bilinear"/>
                            <label class="admin__field-label" for="resize-filter-bilinear">
                                <b>Bilinear</b> - Use an average of a 2x2 environment of pixels.
                            </label>
                        </div>
                        <div class="admin__field admin__field-option">
                            <input type="radio"
                                   id="resize-filter-nearest"
                                   class="admin__control-radio"
                                   name="resize-filter-radio" value="nearest"/>
                            <label class="admin__field-label" for="resize-filter-nearest">
                                <b>Nearest</b> - Use the value of nearby translated pixel values.
                            </label>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </fieldset>
    </form>
</script>

<!-- Custom Snippet creation overlay template -->
<script type="text/x-magento-template" id="fastly-custom-snippet-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to create a custom snippet.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/createCustomSnippet'); ?>"
          method="POST"
          id="fastly-custom-snippet-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <div class="admin__field field _required">
                <label for="custom_snippet_name" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="custom_snippet_name"
                           required="required"
                           id="custom_snippet_name"
                           class="admin__control-text required-entry">
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_type" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Type") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="custom_snippet_type" id="custom_snippet_type" class="admin__control-text">
                        <option value="init">init</option>
                        <option value="recv" selected>recv</option>
                        <option value="hit">hit</option>
                        <option value="miss">miss</option>
                        <option value="pass">pass</option>
                        <option value="fetch">fetch</option>
                        <option value="error">error</option>
                        <option value="deliver">deliver</option>
                        <option value="log">log</option>
                        <option value="hash">hash</option>
                        <option value="none">none</option>
                    </select>
                    <div class="admin__field-note">
                        This specifies the location in which to place the snippet when uploaded to Fastly.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_priority" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Priority") ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="custom_snippet_priority"
                           required="required"
                           id="custom_snippet_priority"
                           value="100"
                           class="admin__control-text required-entry">
                    <div class="admin__field-note">
                        For most configurations, the default (100) is best. Priority determines the ordering for
                        multiple snippets. Lower numbers execute first.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_content" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("VCL") ?></span>
                </label>
                <div class="admin__field-control">
                    <textarea rows="10"
                              name="custom_snippet_content"
                              required="required"
                              id="custom_snippet_content"
                              class="admin__control-text required-entry"></textarea>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Custom Snippet edit overlay template -->
<script type="text/x-magento-template" id="fastly-custom-snippet-edit-template">
    <div class="messages">
        <div class="message message-warning fastly-message-warning" style="display: none">
            <?php /* @noEscape */ echo __("You are about to edit a custom snippet.")?>
        </div>
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/editCustomSnippet'); ?>"
          method="POST"
          id="fastly-custom-snippet-edit-form"
          class="form-inline"
          enctype="multipart/form-data">

        <fieldset class="admin__fieldset form-list question">
            <input hidden="hidden" name="original_snippet_name" id="original_snippet_name" class="admin__control-text">
            <div class="admin__field field _required">
                <label for="custom_snippet_name" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Name") ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="custom_snippet_name"
                           required="required"
                           id="custom_snippet_name"
                           class="admin__control-text required-entry">
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_type" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Type") ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="custom_snippet_type" id="custom_snippet_type" class="admin__control-text">
                        <option value="init">init</option>
                        <option value="recv" selected>recv</option>
                        <option value="hit">hit</option>
                        <option value="miss">miss</option>
                        <option value="pass">pass</option>
                        <option value="fetch">fetch</option>
                        <option value="error">error</option>
                        <option value="deliver">deliver</option>
                        <option value="log">log</option>
                        <option value="hash">hash</option>
                        <option value="none">none</option>
                    </select>
                    <div class="admin__field-note">
                        This specifies the location in which to place the snippet when uploaded to Fastly.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_priority" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("Priority") ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="custom_snippet_priority"
                           required="required"
                           id="custom_snippet_priority"
                           value="100"
                           class="admin__control-text required-entry">
                    <div class="admin__field-note">
                        For most configurations, the default (100) is best. Priority determines the ordering for
                        multiple snippets. Lower numbers execute first.
                    </div>
                </div>
            </div>
            <div class="admin__field field _required">
                <label for="custom_snippet_content" class="admin__field-label">
                    <span><?php /* @noEscape */ echo __("VCL") ?></span>
                </label>
                <div class="admin__field-control">
                    <textarea rows="10"
                              name="custom_snippet_content"
                              required="required"
                              id="custom_snippet_content"
                              class="admin__control-text required-entry"></textarea>
                </div>
            </div>
        </fieldset>
    </form>
</script>

<!-- Modly active module overlay template -->
<script type="text/x-magento-template" id="modly-active-module-template">
    <div class="messages module-messages">
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/setActiveModuleConfig'); ?>"
          method="POST"
          id="fastly-active-module-config-form"
          class="form-inline"
          enctype="multipart/form-data"
          style="margin-top: 25px;">
        <fieldset class="admin__fieldset form-list question">
            <input hidden="hidden" name="module_name" id="module-id" class="admin__control-text">
        </fieldset>
    </form>
</script>

<!-- Modly all modules template -->
<script type="text/x-magento-template" id="modly-all-modules-template">
    <div class="messages">
        <div class="message message-error fastly-message-error" style="display: none">
        </div>
        <div class="message message-success fastly-message-success" style="display: none">
        </div>
        <div class="message message-warning fastly-message-warning" style="display: none">
        </div>
    </div>
    <form action="<?php /* @noEscape */ echo $block->getUrl('adminhtml/fastlyCdn_Vcl/setActiveModules'); ?>"
          method="POST"
          id="modly-all-modules-form"
          class="form-inline"
          enctype="multipart/form-data"
          style="margin-top: 25px;">
        <fieldset class="admin__fieldset form-list question">
            <table class="admin__control-table" id="modly-all-modules-table">
                <thead>
                <tr>
                    <th><?php /* @noEscape */ echo __('Module') ?></th>
                    <th><?php /* @noEscape */ echo __('Description') ?></th>
                    <th class="col-actions" colspan="1"><?php /* @noEscape */ echo __('Enabled') ?></th>
                </tr>
                </thead>
                <tbody class="item-container">
                </tbody>
            </table>
        </fieldset>
    </form>
</script>
<?php

/**
 * AJAX urls passed to uploadvcl.js file
 */
// Advanced
$checkTlsSettingUrl =           $block->getUrl('adminhtml/fastlyCdn_Advanced/checkTlsSetting');
$toggleTlsSettingUrl =          $block->getUrl('adminhtml/fastlyCdn_Advanced/forceTls');
// Backend
$configureBackendUrl =          $block->getUrl('adminhtml/fastlyCdn_Backend/configureBackend');
$fetchBackendsUrl =             $block->getUrl('adminhtml/fastlyCdn_Backend/getBackends');
// Basic Authentication
$createAuthItem =               $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication_Item/create');
$deleteAuthItem =               $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication_Item/delete');
$getAuthItems =                 $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication_Item/listAll');
$checkAuthDictionaryUrl =       $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/checkAuthDictionary');
$checkAuthSettingUrl =          $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/checkAuthSetting');
$checkAuthUsersAvailable =      $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/checkAuthUsersAvailable');
$createAuth =                   $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/create');
$deleteAuth =                   $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/delete');
$toggleAuthSettingUrl =         $block->getUrl('adminhtml/fastlyCdn_BasicAuthentication/enableAuth');
// Blocking
$toggleBlockingSettingUrl =     $block->getUrl('adminhtml/fastlyCdn_Blocking/blocking');
$checkBlockingSettingUrl =      $block->getUrl('adminhtml/fastlyCdn_Blocking/checkBlockingSetting');
$updateBlockingUrl =            $block->getUrl('adminhtml/fastlyCdn_Blocking/updateBlocking');
// Configuration
$isFastlyEnabled =              $block->getConfig()->isFastlyEnabled();
$serviceInfoUrl =               $block->getUrl('adminhtml/fastlyCdn_Configuration/serviceInfo');
$testServiceUrl =               $block->getUrl('adminhtml/fastlyCdn_Configuration/testConnection');
$isAlreadyConfiguredUrl =       $block->getUrl('adminhtml/fastlyCdn_Configuration/isAlreadyConfigured');
$getFastlyServiceInfoUrl =      $block->getUrl('adminhtml/fastlyCdn_Configuration/getFastlyServiceInfo');
// Custom Snippet
$createCustomSnippetUrl =       $block->getUrl('adminhtml/fastlyCdn_CustomSnippet/createCustomSnippet');
$deleteCustomSnippet =          $block->getUrl('adminhtml/fastlyCdn_CustomSnippet/deleteCustomSnippet');
$getCustomSnippetsUrl =         $block->getUrl('adminhtml/fastlyCdn_CustomSnippet/getCustomSnippets');
$getCustomSnippet =             $block->getUrl('adminhtml/fastlyCdn_CustomSnippet/getCustomSnippet');
// Edge ACL
$createAcl =                    $block->getUrl('adminhtml/fastlyCdn_Edge_Acl/create');
$deleteAcl =                    $block->getUrl('adminhtml/fastlyCdn_Edge_Acl/delete');
$listAcls =                     $block->getUrl('adminhtml/fastlyCdn_Edge_Acl/listAll');
$aclItems =                     $block->getUrl('adminhtml/fastlyCdn_Edge_Acl_Item/listAll');
$createAclItem =                $block->getUrl('adminhtml/fastlyCdn_Edge_Acl_Item/create');
$deleteAclItem =                $block->getUrl('adminhtml/fastlyCdn_Edge_Acl_Item/delete');
// Edge Dictionary
$createDictionary =             $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary/create');
$deleteDictionary =             $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary/delete');
$listDictionaries =             $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary/listAll');
$dictionaryItems =              $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary_Item/listAll');
$createDictionaryItem =         $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary_Item/create');
$deleteDictionaryItem =         $block->getUrl('adminhtml/fastlyCdn_Edge_Dictionary_Item/delete');
// Image Optimization
$checkImageSettingUrl =         $block->getUrl('adminhtml/fastlyCdn_ImageOptimization/checkImageSetting');
$checkFastlyIoSettingUrl =      $block->getUrl('adminhtml/fastlyCdn_ImageOptimization/checkFastlyIoSetting');
$toggleImageSettingUrl =        $block->getUrl('adminhtml/fastlyCdn_ImageOptimization/pushImageSettings');
$listIoDefaultConfigOptions =   $block->getUrl('adminhtml/fastlyCdn_ImageOptimization/listAll');
$configureIoUrl =               $block->getUrl('adminhtml/fastlyCdn_ImageOptimization/ioDefaultConfigOptions');
$isIoEnabled =                  $block->getConfig()->isImageOptimizationEnabled();
// Manifest
$createManifestsUrl =           $block->getUrl('adminhtml/fastlyCdn_Manifest/Create');
$toggleModulesUrl =             $block->getUrl('adminhtml/fastlyCdn_Manifest/ToggleModules');
$getAllModulesUrl =             $block->getUrl('adminhtml/fastlyCdn_Manifest/getAllModules');
$saveModuleConfigUrl =          $block->getUrl('adminhtml/fastlyCdn_Manifest/save');
$getActiveModulesUrl =          $block->getUrl('adminhtml/fastlyCdn_Manifest/getActiveModules');
$getModuleDataUrl =             $block->getUrl('adminhtml/fastlyCdn_Manifest/getModuleData');
$getAllConditionsUrl =          $block->getUrl('adminhtml/fastlyCdn_Manifest/getAllConditions');
$getAllDomainsUrl =             $block->getUrl('adminhtml/fastlyCdn_Manifest/getAllDomains');
$getCountriesUrl =              $block->getUrl('adminhtml/fastlyCdn_Manifest/getCountries');
$uploadModuleSnippetUrl =       $block->getUrl('adminhtml/fastlyCdn_Manifest/upload');
// Synthetic Pages
$getErrorPageRespObjUrl =       $block->getUrl('adminhtml/fastlyCdn_SyntheticPages/getErrorPageRespObj');
$getWafPageRespObjUrl =         $block->getUrl('adminhtml/fastlyCdn_SyntheticPages/getWafPageRespObj');
$savePageErrorHtml =            $block->getUrl('adminhtml/fastlyCdn_SyntheticPages/saveErrorPageHtml');
$saveWafPage =                  $block->getUrl('adminhtml/fastlyCdn_SyntheticPages/saveWafPage');
// VCL
$vclUploadUrl =                 $block->getUrl('adminhtml/fastlyCdn_Vcl/upload');
// Web Application Firewall
$getWafSettingsUrl =            $block->getUrl('adminhtml/fastlyCdn_Waf/getWafSettings');
$getOwaspSettingsUrl =          $block->getUrl('adminhtml/fastlyCdn_Waf/getOwaspSettings');
// This flag is used to prevent calling ajax requests if fastly extension is not selected as caching application
$isFastlyEnabled =              $block->getConfig()->isFastlyEnabled();
?>

<script type="text/x-magento-init">
        {
            "*": {
                "Fastly_Cdn/js/init": {
                    "serviceInfoUrl": "<?php echo $block->escapeJsQuote($serviceInfoUrl);?>",
                    "vclUploadUrl": "<?php echo $block->escapeJsQuote($vclUploadUrl);?>",
                    "testServiceUrl": "<?php echo $block->escapeJsQuote($testServiceUrl);?>",
                    "checkTlsSettingUrl": "<?php echo $block->escapeJsQuote($checkTlsSettingUrl);?>",
                    "toggleTlsSettingUrl": "<?php echo $block->escapeJsQuote($toggleTlsSettingUrl);?>",
                    "checkImageSettingUrl": "<?php echo $block->escapeJsQuote($checkImageSettingUrl);?>",
                    "checkFastlyIoSettingUrl": "<?php echo $block->escapeJsQuote($checkFastlyIoSettingUrl);?>",
                    "toggleImageSettingUrl": "<?php echo $block->escapeJsQuote($toggleImageSettingUrl);?>",
                    "checkBlockingSettingUrl": "<?php echo $block->escapeJsQuote($checkBlockingSettingUrl);?>",
                    "toggleBlockingSettingUrl": "<?php echo $block->escapeJsQuote($toggleBlockingSettingUrl);?>",
                    "isFastlyEnabled": "<?php echo $block->escapeJsQuote($isFastlyEnabled);?>",
                    "isIoEnabled": "<?php echo $block->escapeJsQuote($isIoEnabled);?>",
                    "fetchBackendsUrl": "<?php echo $block->escapeJsQuote($fetchBackendsUrl);?>",
                    "configureBackendUrl": "<?php echo $block->escapeJsQuote($configureBackendUrl);?>",
                    "isAlreadyConfiguredUrl": "<?php echo $block->escapeJsQuote($isAlreadyConfiguredUrl);?>",
                    "saveErrorPageHtmlUrl": "<?php echo $block->escapeJsQuote($savePageErrorHtml);?>",
                    "saveWafPageUrl": "<?php echo $block->escapeJsQuote($saveWafPage);?>",
                    "getErrorPageRespObj": "<?php echo $block->escapeJsQuote($getErrorPageRespObjUrl);?>",
                    "getWafPageRespObj": "<?php echo $block->escapeJsQuote($getWafPageRespObjUrl);?>",
                    "createDictionary": "<?php echo $block->escapeJsQuote($createDictionary);?>",
                    "deleteDictionary": "<?php echo $block->escapeJsQuote($deleteDictionary);?>",
                    "getDictionaries": "<?php echo $block->escapeJsQuote($listDictionaries);?>",
                    "getDictionaryItems": "<?php echo $block->escapeJsQuote($dictionaryItems);?>",
                    "createDictionaryItem": "<?php echo $block->escapeJsQuote($createDictionaryItem);?>",
                    "deleteDictionaryItem": "<?php echo $block->escapeJsQuote($deleteDictionaryItem);?>",
                    "createAcl": "<?php echo $block->escapeJsQuote($createAcl);?>",
                    "deleteAcl": "<?php echo $block->escapeJsQuote($deleteAcl);?>",
                    "deleteCustomSnippet": "<?php echo $block->escapeJsQuote($deleteCustomSnippet);?>",
                    "getCustomSnippet": "<?php echo $block->escapeJsQuote($getCustomSnippet);?>",
                    "getAcls": "<?php echo $block->escapeJsQuote($listAcls);?>",
                    "getAclItems": "<?php echo $block->escapeJsQuote($aclItems);?>",
                    "createAclItem": "<?php echo $block->escapeJsQuote($createAclItem);?>",
                    "deleteAclItem": "<?php echo $block->escapeJsQuote($deleteAclItem);?>",
                    "getAuths": "<?php echo $block->escapeJsQuote($getAuthItems);?>",
                    "createAuth": "<?php echo $block->escapeJsQuote($createAuth);?>",
                    "deleteAuth": "<?php echo $block->escapeJsQuote($deleteAuth);?>",
                    "createAuthItem": "<?php echo $block->escapeJsQuote($createAuthItem);?>",
                    "deleteAuthItem": "<?php echo $block->escapeJsQuote($deleteAuthItem);?>",
                    "checkAuthSettingUrl": "<?php echo $block->escapeJsQuote($checkAuthSettingUrl);?>",
                    "checkAuthDictionaryUrl": "<?php echo $block->escapeJsQuote($checkAuthDictionaryUrl);?>",
                    "toggleAuthSettingUrl": "<?php echo $block->escapeJsQuote($toggleAuthSettingUrl);?>",
                    "checkAuthUsersAvailable": "<?php echo $block->escapeJsQuote($checkAuthUsersAvailable);?>",
                    "listIoDefaultConfigOptions": "<?php echo $block->escapeJsQuote($listIoDefaultConfigOptions);?>",
                    "toggleModulesUrl": "<?php echo $block->escapeJsQuote($toggleModulesUrl);?>",
                    "configureIoUrl": "<?php echo $block->escapeJsQuote($configureIoUrl);?>",
                    "createCustomSnippetUrl": "<?php echo $block->escapeJsQuote($createCustomSnippetUrl);?>",
                    "getCustomSnippetsUrl": "<?php echo $block->escapeJsQuote($getCustomSnippetsUrl);?>",
                    "createManifestsUrl": "<?php echo $block->escapeJsQuote($createManifestsUrl);?>",
                    "getAllModulesUrl": "<?php echo $block->escapeJsQuote($getAllModulesUrl);?>",
                    "saveModuleConfigUrl": "<?php echo $block->escapeJsQuote($saveModuleConfigUrl);?>",
                    "getActiveModulesUrl": "<?php echo $block->escapeJsQuote($getActiveModulesUrl);?>",
                    "getModuleDataUrl": "<?php echo $block->escapeJsQuote($getModuleDataUrl);?>",
                    "getAllConditionsUrl": "<?php echo $block->escapeJsQuote($getAllConditionsUrl);?>",
                    "getAllDomainsUrl": "<?php echo $block->escapeJsQuote($getAllDomainsUrl);?>",
                    "getCountriesUrl": "<?php echo $block->escapeJsQuote($getCountriesUrl);?>",
                    "uploadModuleSnippetUrl": "<?php echo $block->escapeJsQuote($uploadModuleSnippetUrl);?>",
                    "updateBlockingUrl": "<?php echo $block->escapeJsQuote($updateBlockingUrl);?>",
                    "getFastlyServiceInfoUrl": "<?php echo $block->escapeJsQuote($getFastlyServiceInfoUrl);?>",
                    "getWafSettingsUrl": "<?php echo $block->escapeJsQuote($getWafSettingsUrl);?>",
                    "getOwaspSettingsUrl": "<?php echo $block->escapeJsQuote($getOwaspSettingsUrl);?>"
                }
            }
        }
</script>

<style type="text/css">
    #backend-upload-form {
        margin-top: 25px;
    }

    .dictionary-items-field {
        width: 100%;
    }

    .highlighted > td{
        background: #fffbbb;
    }

    .admin__control-table .fastly-save-action::before {
        content: '\1F4BE';
        font-size: 2rem;
    }

</style>