<div id="historic-toolbar">
    <div id="time-range">
        <div id="historic-from">
            <input name="from" id="from-picker" class="from-picker"/>
            <button type="button" style="display:none;" class="ui-datepicker-trigger '
            .'v-middle"><span>Select Date</span></button>
        </div>
        <div id="historic-to">
            <input name="to" id="to-picker" class="to-picker"/>
            <button type="button" style="display:none;" class="ui-datepicker-trigger '
            .'v-middle"><span>Select Date</span></button>
        </div>
    </div>
    <div id="options">

    </div>
    <button type="submit" id="apply-historic-stats">Apply</button>
</div>
<?php
    $applyHistoricStatsURL = $block->getUrl('adminhtml/dashboard/apply');
?>

<script type="text/x-magento-init">
        {
            "*": {
                "historicStats": {
                    "applyHistoricStatsURL": "<?php echo $block->escapeJsQuote($applyHistoricStatsURL);?>"
                }
            }
        }
</script>